# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.1

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements/pipeline.txt
          # We need to clone and install manually for now because pip install prody 1.9.4 is broken
          - git clone https://github.com/prody/ProDy.git /tmp/prody
          - pushd /tmp/prody
          - python setup.py install
          - popd
          - pip install pytest
          - python setup.py test
