# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0093_order_wholesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('w', 'Wholesale'), ('r', 'Retail')], max_length=50, null=True, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wholesale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.WholesaleAccounts', verbose_name='Wholesale Account'),
        ),
    ]
