# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0094_auto_20180510_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_closing_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True)),
                ('shift_starting_time', models.TimeField(blank=True)),
                ('total_sales', models.FloatField(default=0)),
                ('total_closing_cost', models.FloatField(default=0)),
                ('opening_balance', models.FloatField(default=0)),
                ('shift_ending_time', models.TimeField(blank=True)),
                ('cashier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OCB', to='pretixbase.Event')),
            ],
        ),
    ]
