# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-01 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170701_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[[b'blog', b'blog'], [b'flatpage', b'flatpage']], default=b'blog', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='template',
            field=models.CharField(choices=[(b'default', b'default')], default=b'default', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
