# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-16 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170701_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name=b'Publish On'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.TextField(blank=True, help_text=b'A short description to show in front page feed.', null=True),
        ),
    ]
