# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170716_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, help_text=b'Only used for type flatpage. Url should start and end with "/"', max_length=200, null=True),
        ),
    ]
