# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 16:31
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
