# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-12 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
