# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-24 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post__slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
