# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170824_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='header',
            field=models.CharField(blank=True, default=b'Featured Event', max_length=32, null=True),
        ),
    ]
