XX XXXXXXX

XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX

XX XXXXXXXXX
   XXXXXXXXXX X

   XXXXXXXXXXXX
   XXXXXXXX
   XXXXXXX

XXXXXXXXXXXXXXX XX X XXXX XXXXXX XXXXX XXXXXX XXX XXX XXX XX XXXXX XXXXXXX
XXXXXXX XX XXXX XXXXX XXXXXX XXX XXXXXX XX X XXXXXX XXXXX XXX XXX XX XXXXXX
XX XXX XXXXXX XXXXXX

XXXXX XXXXXXXXX

    XXXX XXXXXXXX XXXXXX XXXXXXXXXX

    X X XXXXXXXXXXXX                       X XXXXX X XXX XXXXX XXXXX
    XXXXXXXXXXXXX XX XXXX XXXX XXXXXXXX    X XXXXXXX XX XXXXX
           XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXX
        X XXX XXXXXXX XXXX XXXXX
        XXXXXXXXXXX XXXXXX XXXXXXX         X XXXXXXX XX XXXXX XX XXX XXXX XXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXX  X XX XXXX XXX XXXXXXXX XX XXX XXXXXX
    XXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXX XXX XX XXXXX XXXXXXX XXX XXXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXX


XXXXXX XXX XX XXXXXXX XX X XXXXXX XXXXXX XXX XXXX XXXXXXXX XXXX XXX XXXX
XX XXX XXXXXX XXX XXXXXX XX XXX XXXX XXXXX XXX XXXXXXXXXXXX

XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXX XXX X

XX XXXXXX
    XXXXX XXXXXXX XXXXXXXX XXXX XXX XXXXXXXX XX XX X XXXXXXXXXXX XXX XXXX
    XXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXX XX XXX

    XXXXXXXXXXXXXXX XXXXXX XXXX XXXX XX X XXXXXXX XXXXXXXX XXXXXX XX XXXX XXX XXXXX
    XXXX XXXXXXX X XXX XXXXXXX XXXXXXXXX XXX XXXXXX XX XXXXXXX XXXXX XX XX XXXX
    XXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXXXX

