
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-18T17:05:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "836c4cf297fe4af56b595db112d16f0d7720a65a",
 "version": "0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
