language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

before_install:
  - pip install coverage mock
  - pip install coveralls requests
  - pip install -r tests/requirements.txt

install: pip install -r requirements.txt

script: make test

after_success: coveralls

notifications:
  email:
    recipients:
      - nathan.danielsen@gmail.com
    on_success: change
on_failure: always
