
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d88914025b136ec9510aed2435a08ad93c27f276",
 "version": "1942"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
