# Generated by Django 2.0.4 on 2018-04-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180430_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='page',
            field=models.CharField(default='/', max_length=500),
        ),
    ]
