apiVersion: v1
kind: Namespace
metadata:
  name: nfs
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: nfs
#  namespace: nfs
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "madcore-nfs"
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 10Gi
