
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-13T11:02:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fa49e7178888610051469f4ff110e28b143807b",
 "version": "5.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
