
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-18T07:42:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b691c4a7de93a5101b0ce6635aaadefd9f859005",
 "version": "v0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
