
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-15T11:14:30-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c5db2d09994a21ab84e14274cef5dc1564858e2",
 "version": "0.1.0-alpha"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
