__version__ = '0.1.2'
__title__ = 'omterms'
__description__ = 'A customizable keyword extraction package.'
__url__ = 'http://github.com/bulentozel/omterms'
__author__ = 'Bulent Ozel'
__author_email__ = 'bulent.ozel@gmail.com'
__license__ = 'Apache2'
__copyright__ = 'Copyright 2018 Bulent Ozel'
