
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-14T13:23:57+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "231059634643af2558d22070f89767410978cf56",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
