
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-27T12:49:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "67d90aaab114e59d178b0c56895de9c9a7f2c5fb",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
