- project:
    check:
      jobs:
        - freezer-api-ubuntu-xenial
        - freezer-api-centos-7:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - freezer-api-ubuntu-xenial
        - openstack-tox-lower-constraints
    experimental:
      jobs:
        - freezer-api-opensuse-423

- job:
    name: freezer-api-ubuntu-xenial
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-api-ubuntu-xenial/run.yaml
    post-run: playbooks/legacy/freezer-api-ubuntu-xenial/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin

- job:
    name: freezer-api-centos-7
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-api-centos-7/run.yaml
    post-run: playbooks/legacy/freezer-api-centos-7/post.yaml
    timeout: 7800
    nodeset: legacy-centos-7
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin

- job:
    name: freezer-api-opensuse-423
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-api-opensuse-423/run.yaml
    post-run: playbooks/legacy/freezer-api-opensuse-423/post.yaml
    timeout: 7800
    nodeset: legacy-opensuse-423
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin
