# Generated by Django 2.0.4 on 2018-05-02 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAuthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAuthProfile',
            fields=[
                ('baseauthprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unicampauth.BaseAuthProfile')),
                ('resource_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('unicampauth.baseauthprofile',),
        ),
        migrations.AddField(
            model_name='baseauthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
