
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-27T09:29:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c762fb1f31a636e4fbac8516ddd98dbd12a90c8",
 "version": "0.0.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
