
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-27T21:59:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee3c8d453910862b5969d6d0762a1eb50028dbb4",
 "version": "3.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
