
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-01T08:10:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0aa72ee4ff7d9b461bf3e113238349a1b24f15d6",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
