
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-19T12:42:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8be85ed6f765e4e1b1311991aac528aa5103aa0",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
