
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6ea75ea43ef0c8b978ff7843a6aef55ca3647a2d",
 "version": "v0.1.1-alpha.post.dev33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
