
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-07T12:01:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e0c27bf5a9525522f301431dd302b3d4167a91e",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
