
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-18T20:02:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "13ff87acf0b67702d4770dac24bb86da7dbd6b66",
 "version": "2.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
