[tool.poetry]
name = "pendulum"
version = "1.5.1"
description = "Python datetimes made easy."

license = "MIT"

authors = [
    "Sébastien Eustace <sebastien@eustace.io>"
]

readme = 'README.rst'

homepage = "https://pendulum.eustace.io"
repository = "https://github.com/sdispater/pendulum"

keywords = ['datetime', 'date', 'time', 'timezone']

build = "build.py"


[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
python-dateutil = "^2.6"
tzlocal = "^1.5"
pytzdata = ">=2018.3"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
pytest-cov = "^2.4"
pytz = ">=2018.3"
sphinx = "^1.7"
