# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_competition', '0002_auto_20180317_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['group__competition', 'entry', 'group__date_voted']},
        ),
        migrations.AlterModelOptions(
            name='votegroup',
            options={'ordering': ['competition', 'date_voted']},
        ),
    ]
