
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-10T11:18:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "842071270c307376bf37933d8d7f78dbf6ff8ccb",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
