
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-10T16:17:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "df4c8dba061a4d7e7510e1857f13bbf9a9b7e649",
 "version": "3.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
