name: jira-metrics
channels: !!python/tuple
- defaults
dependencies:
- matplotlib
- numpy
- pandas
- python=3.5.2=0
- scipy
- seaborn
- statsmodels
- pip:
  - dateparser==0.6.0
  - jira==1.0.7
  - jira_metrics_extract

