
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-20T16:07:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6b0f77e521910abf6d93c87faace61746d3d576",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
