sudo: false
matrix:
  include:
    - env: TEST='pytest' DEPLOYER=true
      language: python
      python: '3.6'
      install: pip install --upgrade 'pip>=9' setuptools_scm
      script: python setup.py test
    - env: TEST='github-tag-version --dry-run'
      language: python
      python: '3.6'
      install:
      - pip install --upgrade 'pip>=9' setuptools_scm
      - python setup.py sdist
      - pip install dist/sqre-codekit-*.tar.gz
      script: |
        if [[ $TRAVIS_SECURE_ENV_VARS == true ]]; then
          github-tag-version \
            --dry-run \
            --org 'lsst' \
            --team 'Data Management' \
            --team 'DM Externals' \
            --email 'sqre-admin@lists.lsst.org' \
            --user 'sqreadmin' \
            --token "$SQREADMIN_TOKEN" \
            --debug \
            'w.2018.18' 'b3595'
        else
          echo "Unable to test without travis secure env vars."
        fi
    - env: TEST='github-tag-teams --dry-run'
      language: python
      python: '3.6'
      install:
      - pip install --upgrade 'pip>=9' setuptools_scm
      - python setup.py sdist
      - pip install dist/sqre-codekit-*.tar.gz
      script: |
        if [[ $TRAVIS_SECURE_ENV_VARS == true ]]; then
          github-tag-teams \
            --dry-run \
            --org 'lsst' \
            --team 'DM Auxilliaries' \
            --token "$SQREADMIN_TOKEN" \
            --user 'sqreadmin' \
            --email 'sqre-admin@lists.lsst.org' \
            --debug \
            --tag 'foo' \
            --tag '13.0' \
            --tag '14.0' \
            --tag '15.0' \
            --tag 'w.2018.18'
        else
          echo "Unable to test without travis secure env vars."
        fi
    - env: TEST=hadolint
      language: c
      services:
        - docker
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/Dockerfile )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        for f in "${CHECK[@]}"; do
          docker run -ti -v$(pwd):$(pwd) -w $(pwd) \
            hadolint/hadolint hadolint "$f"
        done
    - env: TEST=make
      language: c
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/Makefile )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        for f in "${CHECK[@]}"; do
          ( set -e
            cd $(dirname "$f")
            echo "checking $f"
            make --dry-run --warn-undefined-variables
          )
        done
    - env: TEST=markdownlint
      language: c
      services:
        - docker
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/*.md )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        docker run -ti -v $(pwd):$(pwd) -w $(pwd) \
          mivok/markdownlint:0.4.0 "${CHECK[@]}"
env:
  global:
  - secure: WEvb3zfO3XL0vUqIyckr3qZ7RWP5Iw9Pxbgw2Ei8tB8FSqz5DzU99xwl+ucTDQXIGYs4M1ROnf0hpCPP9OM0eSZaRPTf8BEK0SNjDEIQO4Rc89dskNqhf1CFQnCauJhk2ZJ/q0i4J9dV/igN6Ub/3kMRHov6i1UTfqs6ixfo3Fg=
deploy:
  provider: pypi
  user: sqre-admin
  skip_upload_docs: true
  distributions: sdist bdist_wheel
  password:
    secure: f88F6UgUAxe73pQuX5yGHdl96e/dcQIFClBc6mNgzAVDjxWXskQ/YRCcbO81yxdjsQRfBJsOiiQKcuM76k1iaOQTazQtdG2Wc/S29qzLlReBNTvo4iMBTg1TDSkT5RnDKrxG4omphlgJP2C9i+b0TjDcKJ26uh8t6m6eUs/Mffw=
  on:
    tags: true
    branch: master
    condition: "$DEPLOYER = true"
    repo: lsst-sqre/sqre-codekit
branches:
  only:
  - master
  # also matched against tag pushes
  - /^\d+\.\d+\.\d+$/
notifications:
  email: false
