
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-14T21:05:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b827d3d94a4784547cdb962e3e6fa242ee625e0f",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
