pipelines:
  dima:
        label: 'dima'
        description: 'DiMA - Snakemake pipeline to map DNA datasets to a given reference
        genome using widely adopted tools as BWA and Samtools.'
        url: "https://github.com/gmauro/dima"
        type: "git"
        playbook: 'install_pipeline.yaml'
        playbook_vars_template:
                create_venv: True
                project_name: 'noname_project'
                project_email_address: 'example@example'
                project_config_file: 'config.test.data.json'
                miniconda_dir: /path/to/miniconda
                project_dir: /path/where/install/the/pipeline
                references_dir: /path/to/references
                datasets_dir: /path/to/datasets
                tmp_dir: path/to/tmp
#                cluster_setup: True
#                default_host_group: "cluster parameters"
                jobs: 4
  ride:
        label: 'ride'
        description: 'Snakemake enabled pipeline for quantifying abundances of transcripts from RNA-Seq data'
        url: "https://bitbucket.org/biopipelines/ride.git"
        type: "git"
        playbook: 'install_pipeline.yaml'
        playbook_vars_template:
                create_venv: True
                project_name: 'noname_project'
                project_email_address: 'example@example'
                project_config_file: 'config.test.data.json'
                miniconda_dir: /path/to/miniconda
                project_dir: /path/where/install/the/pipeline
                references_dir: /path/to/references
                datasets_dir: /path/to/datasets
                tmp_dir: path/to/tmp
#                cluster_setup: True
#                default_host_group: "cluster parameters"
                jobs: 4
  sride:
        label: 'sride'
        description: 'Snakemake enabled pipeline for smallRNA-Seq identification'
        url: "https://bitbucket.org/biopipelines/sride.git"
        type: "git"
        playbook: 'install_pipeline.yaml'
        playbook_vars_template:
                create_venv: True
                project_name: 'noname_project'
                project_email_address: 'example@example'
                project_config_file: 'config.testdata.yaml'
                miniconda_dir: /path/to/miniconda
                project_dir: /path/where/install/the/pipeline
                references_dir: /path/to/references
                datasets_dir: /path/to/datasets
                tmp_dir: path/to/tmp
#                cluster_setup: True
#                default_host_group: "cluster parameters"
                jobs: 4

