language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install --editable .
script:
  - pytest
before_deploy:
  - |
    if [ "$TRAVIS_BRANCH" = "dev" ]; then
      sed -i -E "s/^(version = )(.*)/\1\2.$TRAVIS_BUILD_NUMBER/" $TRAVIS_BUILD_DIR/setup.cfg
    elif [ "$TRAVIS_BRANCH" = "master" ]; then
      export RELEASE_VERSION=$(grep "version = " $TRAVIS_BUILD_DIR/setup.cfg | sed "s/version = //")
      export RELEASE_BODY="* [Pyppyn v$RELEASE_VERSION CHANGELOG](https://github.com/YakDriver/pyppyn/blob/$RELEASE_VERSION/CHANGELOG.rst)"
      (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
    fi
deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    user: YakDriver
    password:
      secure: Ll07zP0rCGNtI60s3UFpYx9DRqoHMdKVEaGN7NnoFbPJtc+0wi4NE8ZlQXDCvdndDowiolJD5l0n/kO1XM7RSkaYpkSq7uHkOKnwvGPfVD9jt7aHkMT0hxij42v0+mbp/gxJZG0K+oouq34O6CgGzR9OOM8/6Z9xkMp72m0ULkIQ6SJyYPZ95zFeHumBLTRUWYhw/6jQNsTmyVwB1gSiB12dj2PkrlkZfXuZpy+QgwO2lmcl/b5jvWk8gPv1DxggV4FmaaXXlaJkV3+LSpIs0aiXX1vmS2Z+UXqJ2F9TY9d57b/Rk2bz7E5biVlJRSkLYyRteZUjzmeENZi20nX5t8DKB0EhJ5G6toEphTIY0SLLpbCWtmi5e/wv6FzZPvb86t9IJgp8kEZKHukofo4MwysXnt1fUGyqHpZeK8cGx68+QKisGsvrAkDqWrzeUR6IBS50hQbcOua2uVFgBui3jh3+TuTEiSNtED4DucEIi2RaVJBHGPiFM+ZV7hy3DSB6gGfLGmsC9NmUsZrJ5jMJXmKsCmOuttz7YszdeGbNLcv7lBlvDU4tA+6kWPXG9Wj4t326GnSvuHS7q5684Cv6cq/u4iI7bqS0RoQ8QbsRqANxWoBeo3X0AWdi6xsz/83ljMzROLTxV75BCgPXUeIL9iTY26owGw2hE6LDRkUitXI=
    skip_cleanup: true
    skip_upload_docs: true
    on:
      branch: dev
      repo: YakDriver/pyppyn
      python: "3.6"
  - provider: releases
    name: $RELEASE_VERSION
    tag_name: $RELEASE_VERSION
    target_commitish: $TRAVIS_COMMIT
    body: $RELEASE_BODY
    draft: false
    skip_cleanup: true
    api_key:
      secure: l4kaAXn8uUthiplq1YIUscMCu2KNfqUqgr+2OoDZNo/imscnd6puqxgHnWflXdVkL1hvYl3eGgOQ6n1CWlEO/9bMV3mg4U/Gk7DhXUdfDKhxS3xPW5eSi03zfR3EuxFBEMAzCWrPFgwD/lZYp3JWUQMzR6HgTRalQEj6vUUiyqkfsPg0IytPD1yhBJ+3Q3IfB8qk/kL6WM0PkoPHpd1yBLJDkPOz0ZxfGGgajX2/PMeHcx8LtBosYoMDLuYX1Ms8OwXCf2RjSqs4r53T6KNAxTXmmZ8CgIT9eqbNcDJXu4ZwQCS74cw5revj5nSdR6OWCWNl+12Ysy7Dl2lTH82hgbKeuNRTrOWa1mKBN+jiGqdlbPM9ifUDviasfbADZ4+7R3lim69Bi5b2wys7JxublE8oCrrQc4DnIF5goS8Vsymrzc79/1oiwwoRZDLafM7CQKd6tuMrvoJDoe4XMPJiD3Z77T5DJTpGnIX4+cRPA2i5LkXaiH4Jl6wA4dl9sDtvdX+5QDn0V1UAH1uNKByYtHo0v8xzTz7sEfPNcfM5SFPXOTNgnWf+ki8JxbEVrAtr3GC3B4ZptUx+ci35lFwe3pqVLWprwBB91k/Cudq/JTQJTOv2N8+aiIE5Gjn5zL6QgC2YcSAn/DGgUAQKlmwm++paygpNFv/7KkwP991H4bw=
    on:
      branch: master
      repo: YakDriver/pyppyn
      python: "3.6"
  - provider: pypi
    distributions: sdist bdist_wheel
    user: YakDriver
    password:
      secure: msxEPL7wdduLIN+T9xm58nsN2of/wqUU985oJUjsTx6AiUBJFBfLeo/xJ92ne93ZSnlJA29Pj2zi6DeW2o9hJ/WhPoicBUdpQCdTEfsKZGS2CXHVQLg8D5njJi32EWha9dV5PicwQwxN1olHtG1KrU5N/NljWWvMuK3UHy74BSnikxu8s7t9Tww5umlecd8rQGyARipdQGOUQDmJre5RMmFSldmnQ+TkO47uBMkhdvbnixoqM2sAyqeQ198G4nL35bx7zSGuhZjcdS8UgSz+QeAyx9wDiwqEb6GgR+zJMU934bLMtNgV0sfHYsvm6Pkg5HnCmpPieXBYjCtjeJNIeZVGsP4Speq/Q7nKoxx/Yl1/CtBCX5qEUzjcZo0YizA5ipeYzz1jios9XkDbignJAW5iy4M6MKVdSn5XOW0Qsg6CzEJJGyR+5lsVc3okU2MaRmXKA2PdldknEsgGjy5zc75jXjEfWRQsuM1Tp6dFN3898mjYjmJfFQK8z74sq7IJXQYHi00nmslgkWEJVgOqRydAn+vqy9ug3h6dqw+0BK7A/tg28HkCucG9/eMyqcZT2yYulKSxy7E5C55nmzajVhD5RqIM561dNsmq8mpuJpWlp8RIQKgb5WAPQ/52T/3T+R/tc2vGFc/Ra7dXHygrQHfFSbD/dl4nNQY8rMmWLek=
    skip_upload_docs: true
    on:
      tags: true
      repo: YakDriver/pyppyn
      python: "3.6"
