[tool.poetry]
name = "figga"
version = "0.1.2"
description = "A simple configuration manager for Python."
authors = ["Berislav Lopac <berislav@lopac.net>"]
readme = 'README.md'
repository = "https://github.com/berislavlopac/figga"
homepage = "https://github.com/berislavlopac/figga"
keywords = ["configuration", "config"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
