
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-02T00:49:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c9513586f076f85ae2dd6be97598d5d5f4824be",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
