# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Content')),
                ('relative_path', models.TextField()),
                ('digest', models.TextField()),
            ],
            bases=('pulp_app.content',),
        ),
        migrations.CreateModel(
            name='FilePublisher',
            fields=[
                ('publisher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Publisher')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.publisher',),
        ),
        migrations.CreateModel(
            name='FileRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Remote')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.remote',),
        ),
        migrations.AlterUniqueTogether(
            name='filecontent',
            unique_together=set([('relative_path', 'digest')]),
        ),
    ]
