environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python35"
    - PYTHON: "C:/Python36"
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python34-x64"
    - PYTHON: "C:/Python35-x64"
    - PYTHON: "C:/Python36-x64"
install:
    - "SET PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%"
    - "python --version"
    - "IF %PYTHON:~-4% == -x64 (SET ARCH=x64) ELSE (SET ARCH=i386)"
    - ps: "Start-FileDownload https://mediaarea.net/download/binary/mediainfo/18.05/MediaInfo_CLI_18.05_Windows_${Env:ARCH}.zip"
    - ps: "unzip -o MediaInfo_CLI_18.05_Windows_${Env:ARCH}.zip"
    - ps: "Start-FileDownload https://mediaarea.net/download/binary/libmediainfo0/18.05/MediaInfo_DLL_18.05_Windows_${Env:ARCH}_WithoutInstaller.7z"
    - ps: "7z -y x MediaInfo_DLL_18.05_Windows_${Env:ARCH}_WithoutInstaller.7z"
    - "pip install pytest"
    # see https://phabricator.wikimedia.org/T186991
    # and https://github.com/wikimedia/pywikibot/commit/c503a9bb225933066f2b9f40b061b0279c7f6ad3
    - "IF %PYTHON:~0,11% == C:/Python34 (pip install pytest-runner==3.0) ELSE (pip install pytest-runner)"
build_script:
  - "python setup.py build"
test_script:
  - "python setup.py test"
