# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edocuments/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 525)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../ressources/edocuments.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.search)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.search_text = QtWidgets.QLineEdit(self.search)
        self.search_text.setObjectName("search_text")
        self.verticalLayout_4.addWidget(self.search_text)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search_result_list = QtWidgets.QListWidget(self.search)
        self.search_result_list.setObjectName("search_result_list")
        self.verticalLayout_3.addWidget(self.search_result_list)
        self.search_result_text = QtWidgets.QTextBrowser(self.search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_result_text.sizePolicy().hasHeightForWidth())
        self.search_result_text.setSizePolicy(sizePolicy)
        self.search_result_text.setMinimumSize(QtCore.QSize(0, 0))
        self.search_result_text.setMaximumSize(QtCore.QSize(16777215, 50))
        self.search_result_text.setBaseSize(QtCore.QSize(0, 0))
        self.search_result_text.setObjectName("search_result_text")
        self.verticalLayout_3.addWidget(self.search_result_text)
        self.horizontalWidget = QtWidgets.QWidget(self.search)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget.setBaseSize(QtCore.QSize(0, 0))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.open_folder = QtWidgets.QPushButton(self.horizontalWidget)
        self.open_folder.setObjectName("open_folder")
        self.horizontalLayout.addWidget(self.open_folder)
        self.open = QtWidgets.QPushButton(self.horizontalWidget)
        self.open.setObjectName("open")
        self.horizontalLayout.addWidget(self.open)
        self.verticalLayout_3.addWidget(self.horizontalWidget)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.search, "")
        self.scan = QtWidgets.QWidget()
        self.scan.setObjectName("scan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scan)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.scan)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.scan_type = QtWidgets.QComboBox(self.scan)
        self.scan_type.setObjectName("scan_type")
        self.horizontalLayout_3.addWidget(self.scan_type)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.direct = QtWidgets.QGroupBox(self.scan)
        self.direct.setObjectName("direct")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.direct)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scan_to = QtWidgets.QLineEdit(self.direct)
        self.scan_to.setObjectName("scan_to")
        self.horizontalLayout_5.addWidget(self.scan_to)
        self.scan_browse = QtWidgets.QPushButton(self.direct)
        self.scan_browse.setObjectName("scan_browse")
        self.horizontalLayout_5.addWidget(self.scan_browse)
        self.scan_start = QtWidgets.QPushButton(self.direct)
        self.scan_start.setObjectName("scan_start")
        self.horizontalLayout_5.addWidget(self.scan_start)
        self.verticalLayout_2.addWidget(self.direct)
        self.groupBox = QtWidgets.QGroupBox(self.scan)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scan_comments = QtWidgets.QLabel(self.groupBox)
        self.scan_comments.setText("")
        self.scan_comments.setObjectName("scan_comments")
        self.verticalLayout_6.addWidget(self.scan_comments)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.scan, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 25))
        self.menubar.setObjectName("menubar")
        self.menuUpdate_library = QtWidgets.QMenu(self.menubar)
        self.menuUpdate_library.setObjectName("menuUpdate_library")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.library_update = QtWidgets.QAction(MainWindow)
        self.library_update.setObjectName("library_update")
        self.library_reset = QtWidgets.QAction(MainWindow)
        self.library_reset.setObjectName("library_reset")
        self.library_optimize = QtWidgets.QAction(MainWindow)
        self.library_optimize.setObjectName("library_optimize")
        self.menuUpdate_library.addAction(self.library_update)
        self.menuUpdate_library.addAction(self.library_optimize)
        self.menuUpdate_library.addAction(self.library_reset)
        self.menubar.addAction(self.menuUpdate_library.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "eDocuments - a Simple and Productive Personal Documents Library"))
        self.open_folder.setText(_translate("MainWindow", "Open folder"))
        self.open.setText(_translate("MainWindow", "Open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search), _translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Scan type"))
        self.direct.setTitle(_translate("MainWindow", "Scan"))
        self.scan_browse.setText(_translate("MainWindow", "Browse..."))
        self.scan_start.setText(_translate("MainWindow", "Scan"))
        self.groupBox.setTitle(_translate("MainWindow", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scan), _translate("MainWindow", "Scan"))
        self.menuUpdate_library.setTitle(_translate("MainWindow", "&Library"))
        self.library_update.setText(_translate("MainWindow", "&Update"))
        self.library_reset.setText(_translate("MainWindow", "Reset"))
        self.library_optimize.setText(_translate("MainWindow", "Optimise"))

