
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-27T15:15:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "575c1369e7bc6b4a7bb5644d90a63b0e104f02d4",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
