# Generated by Django 2.0.4 on 2018-04-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hub',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterModelTable(
            name='personastohubs',
            table='personas_to_hubs',
        ),
    ]
