# Generated by Django 2.0.4 on 2018-04-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtable', '0002_auto_20180416_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personastohubs',
            options={'verbose_name_plural': 'PersonasToHubs'},
        ),
    ]
