'''
Created on Jul 21, 2017

@author: Salim
'''




SERIALIZATION_FORMAT_HTTP_FORMAT_FIELD_NAME = "format"
SERIALIZATION_FORMAT_HTTP_FORMAT_FIELD_VERSION = "formatversion"
SERIALIZATION_FORMAT_HTTP_LESS_FIELD_VERSION = "lessversion"



HTTP_PROTOCOL = 'http://'
HTTPS_PROTOCOL = 'https://'


LESS_RPC_REQUEST_PING = "/ping";
LESS_RPC_REQUEST_EXECUTE = "/execute";
LESS_RPC_REQUEST_SERVICE = "/service";
LESS_RPC_REQUEST_INFO = "/info";

HTTP_WAIT_TIME_SHORT = 5    
HTTP_WAIT_TIME_LONG = 60 * 60 * 5