
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-18T08:11:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "45f0da0a3ebed9a19df6085408dc64b08b213c4d",
 "version": "v0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
