
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-29T22:47:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee29ff6930e4fc1857232b405389edf93ea584ff",
 "version": "v0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
