---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy-redis
  namespace: scrapy-cluster
  labels:
    app: scrapy-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapy-redis
  template:
    metadata:
      labels:
        app: scrapy-redis
    spec:
      containers:
      - name: scrapy-redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: scrapy-redis
  namespace: scrapy-cluster
  labels:
    app: scrapy-redis
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app: scrapy-redis

