
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-30T16:26:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "95ed380489764eb0bb210b2fe3ff2db75e3e2654",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
