# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_courier', '0010_sender_recipient_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_code',
            field=models.BooleanField(
                default=False, verbose_name='from code',
                help_text='True if the notification is defined in the '
                          'code and automatically managed'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_model',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=models.deletion.CASCADE,
                related_name='+', to='contenttypes.ContentType',
                verbose_name='recipient model'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender_model',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=models.deletion.CASCADE,
                related_name='+', to='contenttypes.ContentType',
                verbose_name='sender model'),
        ),
        migrations.RemoveField(
            'notification', 'use_sender'),
        migrations.RenameField(
            'notification', 'sender_model', 'source_model'),
        migrations.RemoveField(
            'notification', 'use_recipient'),
        migrations.RenameField(
            'notification', 'recipient_model', 'target_model'),
        migrations.RenameField('template', 'target', 'recipient'),
    ]
