
# Generated by Django 1.10.2 on 2017-03-10 15:31


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestItem',
            new_name='CatalogItem',
        ),
    ]
