
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-23T07:02:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "acaaf7f3c6aa869eb75b083f1676d9c52607981c",
 "version": "0.0.0a12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
