
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-18T13:58:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e594dbef9e2dfe09ee466f6bd961bd63cb46b86c",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
