// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: onnx-operators_ONNX_NAMESPACE-ml.proto

#ifndef PROTOBUF_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto__INCLUDED
#define PROTOBUF_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "onnx_ONNX_NAMESPACE-ml.pb.h"
// @@protoc_insertion_point(includes)

namespace onnx {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();
void protobuf_AssignDesc_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();
void protobuf_ShutdownFile_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();

class OperatorProto;
class OperatorSetProto;

enum OperatorProto_OperatorStatus {
  OperatorProto_OperatorStatus_EXPERIMENTAL = 0,
  OperatorProto_OperatorStatus_STABLE = 1
};
bool OperatorProto_OperatorStatus_IsValid(int value);
const OperatorProto_OperatorStatus OperatorProto_OperatorStatus_OperatorStatus_MIN = OperatorProto_OperatorStatus_EXPERIMENTAL;
const OperatorProto_OperatorStatus OperatorProto_OperatorStatus_OperatorStatus_MAX = OperatorProto_OperatorStatus_STABLE;
const int OperatorProto_OperatorStatus_OperatorStatus_ARRAYSIZE = OperatorProto_OperatorStatus_OperatorStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* OperatorProto_OperatorStatus_descriptor();
inline const ::std::string& OperatorProto_OperatorStatus_Name(OperatorProto_OperatorStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    OperatorProto_OperatorStatus_descriptor(), value);
}
inline bool OperatorProto_OperatorStatus_Parse(
    const ::std::string& name, OperatorProto_OperatorStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OperatorProto_OperatorStatus>(
    OperatorProto_OperatorStatus_descriptor(), name, value);
}
// ===================================================================

class OperatorProto : public ::google::protobuf::Message {
 public:
  OperatorProto();
  virtual ~OperatorProto();

  OperatorProto(const OperatorProto& from);

  inline OperatorProto& operator=(const OperatorProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OperatorProto& default_instance();

  void Swap(OperatorProto* other);

  // implements Message ----------------------------------------------

  OperatorProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OperatorProto& from);
  void MergeFrom(const OperatorProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef OperatorProto_OperatorStatus OperatorStatus;
  static const OperatorStatus EXPERIMENTAL = OperatorProto_OperatorStatus_EXPERIMENTAL;
  static const OperatorStatus STABLE = OperatorProto_OperatorStatus_STABLE;
  static inline bool OperatorStatus_IsValid(int value) {
    return OperatorProto_OperatorStatus_IsValid(value);
  }
  static const OperatorStatus OperatorStatus_MIN =
    OperatorProto_OperatorStatus_OperatorStatus_MIN;
  static const OperatorStatus OperatorStatus_MAX =
    OperatorProto_OperatorStatus_OperatorStatus_MAX;
  static const int OperatorStatus_ARRAYSIZE =
    OperatorProto_OperatorStatus_OperatorStatus_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  OperatorStatus_descriptor() {
    return OperatorProto_OperatorStatus_descriptor();
  }
  static inline const ::std::string& OperatorStatus_Name(OperatorStatus value) {
    return OperatorProto_OperatorStatus_Name(value);
  }
  static inline bool OperatorStatus_Parse(const ::std::string& name,
      OperatorStatus* value) {
    return OperatorProto_OperatorStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string op_type = 1;
  inline bool has_op_type() const;
  inline void clear_op_type();
  static const int kOpTypeFieldNumber = 1;
  inline const ::std::string& op_type() const;
  inline void set_op_type(const ::std::string& value);
  inline void set_op_type(const char* value);
  inline void set_op_type(const char* value, size_t size);
  inline ::std::string* mutable_op_type();
  inline ::std::string* release_op_type();
  inline void set_allocated_op_type(::std::string* op_type);

  // optional int64 since_version = 2;
  inline bool has_since_version() const;
  inline void clear_since_version();
  static const int kSinceVersionFieldNumber = 2;
  inline ::google::protobuf::int64 since_version() const;
  inline void set_since_version(::google::protobuf::int64 value);

  // optional .onnx.OperatorProto.OperatorStatus status = 3;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 3;
  inline ::onnx::OperatorProto_OperatorStatus status() const;
  inline void set_status(::onnx::OperatorProto_OperatorStatus value);

  // optional string doc_string = 10;
  inline bool has_doc_string() const;
  inline void clear_doc_string();
  static const int kDocStringFieldNumber = 10;
  inline const ::std::string& doc_string() const;
  inline void set_doc_string(const ::std::string& value);
  inline void set_doc_string(const char* value);
  inline void set_doc_string(const char* value, size_t size);
  inline ::std::string* mutable_doc_string();
  inline ::std::string* release_doc_string();
  inline void set_allocated_doc_string(::std::string* doc_string);

  // @@protoc_insertion_point(class_scope:onnx.OperatorProto)
 private:
  inline void set_has_op_type();
  inline void clear_has_op_type();
  inline void set_has_since_version();
  inline void clear_has_since_version();
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_doc_string();
  inline void clear_has_doc_string();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* op_type_;
  ::google::protobuf::int64 since_version_;
  ::std::string* doc_string_;
  int status_;
  friend void  protobuf_AddDesc_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();
  friend void protobuf_AssignDesc_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();
  friend void protobuf_ShutdownFile_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();

  void InitAsDefaultInstance();
  static OperatorProto* default_instance_;
};
// -------------------------------------------------------------------

class OperatorSetProto : public ::google::protobuf::Message {
 public:
  OperatorSetProto();
  virtual ~OperatorSetProto();

  OperatorSetProto(const OperatorSetProto& from);

  inline OperatorSetProto& operator=(const OperatorSetProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OperatorSetProto& default_instance();

  void Swap(OperatorSetProto* other);

  // implements Message ----------------------------------------------

  OperatorSetProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OperatorSetProto& from);
  void MergeFrom(const OperatorSetProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string magic = 1;
  inline bool has_magic() const;
  inline void clear_magic();
  static const int kMagicFieldNumber = 1;
  inline const ::std::string& magic() const;
  inline void set_magic(const ::std::string& value);
  inline void set_magic(const char* value);
  inline void set_magic(const char* value, size_t size);
  inline ::std::string* mutable_magic();
  inline ::std::string* release_magic();
  inline void set_allocated_magic(::std::string* magic);

  // optional int32 ir_version = 2;
  inline bool has_ir_version() const;
  inline void clear_ir_version();
  static const int kIrVersionFieldNumber = 2;
  inline ::google::protobuf::int32 ir_version() const;
  inline void set_ir_version(::google::protobuf::int32 value);

  // optional string ir_version_prerelease = 3;
  inline bool has_ir_version_prerelease() const;
  inline void clear_ir_version_prerelease();
  static const int kIrVersionPrereleaseFieldNumber = 3;
  inline const ::std::string& ir_version_prerelease() const;
  inline void set_ir_version_prerelease(const ::std::string& value);
  inline void set_ir_version_prerelease(const char* value);
  inline void set_ir_version_prerelease(const char* value, size_t size);
  inline ::std::string* mutable_ir_version_prerelease();
  inline ::std::string* release_ir_version_prerelease();
  inline void set_allocated_ir_version_prerelease(::std::string* ir_version_prerelease);

  // optional string ir_build_metadata = 7;
  inline bool has_ir_build_metadata() const;
  inline void clear_ir_build_metadata();
  static const int kIrBuildMetadataFieldNumber = 7;
  inline const ::std::string& ir_build_metadata() const;
  inline void set_ir_build_metadata(const ::std::string& value);
  inline void set_ir_build_metadata(const char* value);
  inline void set_ir_build_metadata(const char* value, size_t size);
  inline ::std::string* mutable_ir_build_metadata();
  inline ::std::string* release_ir_build_metadata();
  inline void set_allocated_ir_build_metadata(::std::string* ir_build_metadata);

  // optional string domain = 4;
  inline bool has_domain() const;
  inline void clear_domain();
  static const int kDomainFieldNumber = 4;
  inline const ::std::string& domain() const;
  inline void set_domain(const ::std::string& value);
  inline void set_domain(const char* value);
  inline void set_domain(const char* value, size_t size);
  inline ::std::string* mutable_domain();
  inline ::std::string* release_domain();
  inline void set_allocated_domain(::std::string* domain);

  // optional int64 opset_version = 5;
  inline bool has_opset_version() const;
  inline void clear_opset_version();
  static const int kOpsetVersionFieldNumber = 5;
  inline ::google::protobuf::int64 opset_version() const;
  inline void set_opset_version(::google::protobuf::int64 value);

  // optional string doc_string = 6;
  inline bool has_doc_string() const;
  inline void clear_doc_string();
  static const int kDocStringFieldNumber = 6;
  inline const ::std::string& doc_string() const;
  inline void set_doc_string(const ::std::string& value);
  inline void set_doc_string(const char* value);
  inline void set_doc_string(const char* value, size_t size);
  inline ::std::string* mutable_doc_string();
  inline ::std::string* release_doc_string();
  inline void set_allocated_doc_string(::std::string* doc_string);

  // repeated .onnx.OperatorProto operator = 8;
  inline int operator__size() const;
  inline void clear_operator_();
  static const int kOperatorFieldNumber = 8;
  inline const ::onnx::OperatorProto& operator_(int index) const;
  inline ::onnx::OperatorProto* mutable_operator_(int index);
  inline ::onnx::OperatorProto* add_operator_();
  inline const ::google::protobuf::RepeatedPtrField< ::onnx::OperatorProto >&
      operator_() const;
  inline ::google::protobuf::RepeatedPtrField< ::onnx::OperatorProto >*
      mutable_operator_();

  // @@protoc_insertion_point(class_scope:onnx.OperatorSetProto)
 private:
  inline void set_has_magic();
  inline void clear_has_magic();
  inline void set_has_ir_version();
  inline void clear_has_ir_version();
  inline void set_has_ir_version_prerelease();
  inline void clear_has_ir_version_prerelease();
  inline void set_has_ir_build_metadata();
  inline void clear_has_ir_build_metadata();
  inline void set_has_domain();
  inline void clear_has_domain();
  inline void set_has_opset_version();
  inline void clear_has_opset_version();
  inline void set_has_doc_string();
  inline void clear_has_doc_string();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* magic_;
  ::std::string* ir_version_prerelease_;
  ::std::string* ir_build_metadata_;
  ::std::string* domain_;
  ::google::protobuf::int64 opset_version_;
  ::std::string* doc_string_;
  ::google::protobuf::RepeatedPtrField< ::onnx::OperatorProto > operator__;
  ::google::protobuf::int32 ir_version_;
  friend void  protobuf_AddDesc_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();
  friend void protobuf_AssignDesc_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();
  friend void protobuf_ShutdownFile_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto();

  void InitAsDefaultInstance();
  static OperatorSetProto* default_instance_;
};
// ===================================================================


// ===================================================================

// OperatorProto

// optional string op_type = 1;
inline bool OperatorProto::has_op_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OperatorProto::set_has_op_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OperatorProto::clear_has_op_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OperatorProto::clear_op_type() {
  if (op_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    op_type_->clear();
  }
  clear_has_op_type();
}
inline const ::std::string& OperatorProto::op_type() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorProto.op_type)
  return *op_type_;
}
inline void OperatorProto::set_op_type(const ::std::string& value) {
  set_has_op_type();
  if (op_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    op_type_ = new ::std::string;
  }
  op_type_->assign(value);
  // @@protoc_insertion_point(field_set:onnx.OperatorProto.op_type)
}
inline void OperatorProto::set_op_type(const char* value) {
  set_has_op_type();
  if (op_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    op_type_ = new ::std::string;
  }
  op_type_->assign(value);
  // @@protoc_insertion_point(field_set_char:onnx.OperatorProto.op_type)
}
inline void OperatorProto::set_op_type(const char* value, size_t size) {
  set_has_op_type();
  if (op_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    op_type_ = new ::std::string;
  }
  op_type_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:onnx.OperatorProto.op_type)
}
inline ::std::string* OperatorProto::mutable_op_type() {
  set_has_op_type();
  if (op_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    op_type_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:onnx.OperatorProto.op_type)
  return op_type_;
}
inline ::std::string* OperatorProto::release_op_type() {
  clear_has_op_type();
  if (op_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = op_type_;
    op_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorProto::set_allocated_op_type(::std::string* op_type) {
  if (op_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete op_type_;
  }
  if (op_type) {
    set_has_op_type();
    op_type_ = op_type;
  } else {
    clear_has_op_type();
    op_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:onnx.OperatorProto.op_type)
}

// optional int64 since_version = 2;
inline bool OperatorProto::has_since_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OperatorProto::set_has_since_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OperatorProto::clear_has_since_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OperatorProto::clear_since_version() {
  since_version_ = GOOGLE_LONGLONG(0);
  clear_has_since_version();
}
inline ::google::protobuf::int64 OperatorProto::since_version() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorProto.since_version)
  return since_version_;
}
inline void OperatorProto::set_since_version(::google::protobuf::int64 value) {
  set_has_since_version();
  since_version_ = value;
  // @@protoc_insertion_point(field_set:onnx.OperatorProto.since_version)
}

// optional .onnx.OperatorProto.OperatorStatus status = 3;
inline bool OperatorProto::has_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OperatorProto::set_has_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OperatorProto::clear_has_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OperatorProto::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::onnx::OperatorProto_OperatorStatus OperatorProto::status() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorProto.status)
  return static_cast< ::onnx::OperatorProto_OperatorStatus >(status_);
}
inline void OperatorProto::set_status(::onnx::OperatorProto_OperatorStatus value) {
  assert(::onnx::OperatorProto_OperatorStatus_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:onnx.OperatorProto.status)
}

// optional string doc_string = 10;
inline bool OperatorProto::has_doc_string() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OperatorProto::set_has_doc_string() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OperatorProto::clear_has_doc_string() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OperatorProto::clear_doc_string() {
  if (doc_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_->clear();
  }
  clear_has_doc_string();
}
inline const ::std::string& OperatorProto::doc_string() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorProto.doc_string)
  return *doc_string_;
}
inline void OperatorProto::set_doc_string(const ::std::string& value) {
  set_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_ = new ::std::string;
  }
  doc_string_->assign(value);
  // @@protoc_insertion_point(field_set:onnx.OperatorProto.doc_string)
}
inline void OperatorProto::set_doc_string(const char* value) {
  set_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_ = new ::std::string;
  }
  doc_string_->assign(value);
  // @@protoc_insertion_point(field_set_char:onnx.OperatorProto.doc_string)
}
inline void OperatorProto::set_doc_string(const char* value, size_t size) {
  set_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_ = new ::std::string;
  }
  doc_string_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:onnx.OperatorProto.doc_string)
}
inline ::std::string* OperatorProto::mutable_doc_string() {
  set_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:onnx.OperatorProto.doc_string)
  return doc_string_;
}
inline ::std::string* OperatorProto::release_doc_string() {
  clear_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = doc_string_;
    doc_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorProto::set_allocated_doc_string(::std::string* doc_string) {
  if (doc_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete doc_string_;
  }
  if (doc_string) {
    set_has_doc_string();
    doc_string_ = doc_string;
  } else {
    clear_has_doc_string();
    doc_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:onnx.OperatorProto.doc_string)
}

// -------------------------------------------------------------------

// OperatorSetProto

// optional string magic = 1;
inline bool OperatorSetProto::has_magic() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OperatorSetProto::set_has_magic() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OperatorSetProto::clear_has_magic() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OperatorSetProto::clear_magic() {
  if (magic_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    magic_->clear();
  }
  clear_has_magic();
}
inline const ::std::string& OperatorSetProto::magic() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorSetProto.magic)
  return *magic_;
}
inline void OperatorSetProto::set_magic(const ::std::string& value) {
  set_has_magic();
  if (magic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    magic_ = new ::std::string;
  }
  magic_->assign(value);
  // @@protoc_insertion_point(field_set:onnx.OperatorSetProto.magic)
}
inline void OperatorSetProto::set_magic(const char* value) {
  set_has_magic();
  if (magic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    magic_ = new ::std::string;
  }
  magic_->assign(value);
  // @@protoc_insertion_point(field_set_char:onnx.OperatorSetProto.magic)
}
inline void OperatorSetProto::set_magic(const char* value, size_t size) {
  set_has_magic();
  if (magic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    magic_ = new ::std::string;
  }
  magic_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:onnx.OperatorSetProto.magic)
}
inline ::std::string* OperatorSetProto::mutable_magic() {
  set_has_magic();
  if (magic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    magic_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:onnx.OperatorSetProto.magic)
  return magic_;
}
inline ::std::string* OperatorSetProto::release_magic() {
  clear_has_magic();
  if (magic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = magic_;
    magic_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorSetProto::set_allocated_magic(::std::string* magic) {
  if (magic_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete magic_;
  }
  if (magic) {
    set_has_magic();
    magic_ = magic;
  } else {
    clear_has_magic();
    magic_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:onnx.OperatorSetProto.magic)
}

// optional int32 ir_version = 2;
inline bool OperatorSetProto::has_ir_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OperatorSetProto::set_has_ir_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OperatorSetProto::clear_has_ir_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OperatorSetProto::clear_ir_version() {
  ir_version_ = 0;
  clear_has_ir_version();
}
inline ::google::protobuf::int32 OperatorSetProto::ir_version() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorSetProto.ir_version)
  return ir_version_;
}
inline void OperatorSetProto::set_ir_version(::google::protobuf::int32 value) {
  set_has_ir_version();
  ir_version_ = value;
  // @@protoc_insertion_point(field_set:onnx.OperatorSetProto.ir_version)
}

// optional string ir_version_prerelease = 3;
inline bool OperatorSetProto::has_ir_version_prerelease() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OperatorSetProto::set_has_ir_version_prerelease() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OperatorSetProto::clear_has_ir_version_prerelease() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OperatorSetProto::clear_ir_version_prerelease() {
  if (ir_version_prerelease_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_version_prerelease_->clear();
  }
  clear_has_ir_version_prerelease();
}
inline const ::std::string& OperatorSetProto::ir_version_prerelease() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorSetProto.ir_version_prerelease)
  return *ir_version_prerelease_;
}
inline void OperatorSetProto::set_ir_version_prerelease(const ::std::string& value) {
  set_has_ir_version_prerelease();
  if (ir_version_prerelease_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_version_prerelease_ = new ::std::string;
  }
  ir_version_prerelease_->assign(value);
  // @@protoc_insertion_point(field_set:onnx.OperatorSetProto.ir_version_prerelease)
}
inline void OperatorSetProto::set_ir_version_prerelease(const char* value) {
  set_has_ir_version_prerelease();
  if (ir_version_prerelease_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_version_prerelease_ = new ::std::string;
  }
  ir_version_prerelease_->assign(value);
  // @@protoc_insertion_point(field_set_char:onnx.OperatorSetProto.ir_version_prerelease)
}
inline void OperatorSetProto::set_ir_version_prerelease(const char* value, size_t size) {
  set_has_ir_version_prerelease();
  if (ir_version_prerelease_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_version_prerelease_ = new ::std::string;
  }
  ir_version_prerelease_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:onnx.OperatorSetProto.ir_version_prerelease)
}
inline ::std::string* OperatorSetProto::mutable_ir_version_prerelease() {
  set_has_ir_version_prerelease();
  if (ir_version_prerelease_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_version_prerelease_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:onnx.OperatorSetProto.ir_version_prerelease)
  return ir_version_prerelease_;
}
inline ::std::string* OperatorSetProto::release_ir_version_prerelease() {
  clear_has_ir_version_prerelease();
  if (ir_version_prerelease_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ir_version_prerelease_;
    ir_version_prerelease_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorSetProto::set_allocated_ir_version_prerelease(::std::string* ir_version_prerelease) {
  if (ir_version_prerelease_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ir_version_prerelease_;
  }
  if (ir_version_prerelease) {
    set_has_ir_version_prerelease();
    ir_version_prerelease_ = ir_version_prerelease;
  } else {
    clear_has_ir_version_prerelease();
    ir_version_prerelease_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:onnx.OperatorSetProto.ir_version_prerelease)
}

// optional string ir_build_metadata = 7;
inline bool OperatorSetProto::has_ir_build_metadata() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OperatorSetProto::set_has_ir_build_metadata() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OperatorSetProto::clear_has_ir_build_metadata() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OperatorSetProto::clear_ir_build_metadata() {
  if (ir_build_metadata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_build_metadata_->clear();
  }
  clear_has_ir_build_metadata();
}
inline const ::std::string& OperatorSetProto::ir_build_metadata() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorSetProto.ir_build_metadata)
  return *ir_build_metadata_;
}
inline void OperatorSetProto::set_ir_build_metadata(const ::std::string& value) {
  set_has_ir_build_metadata();
  if (ir_build_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_build_metadata_ = new ::std::string;
  }
  ir_build_metadata_->assign(value);
  // @@protoc_insertion_point(field_set:onnx.OperatorSetProto.ir_build_metadata)
}
inline void OperatorSetProto::set_ir_build_metadata(const char* value) {
  set_has_ir_build_metadata();
  if (ir_build_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_build_metadata_ = new ::std::string;
  }
  ir_build_metadata_->assign(value);
  // @@protoc_insertion_point(field_set_char:onnx.OperatorSetProto.ir_build_metadata)
}
inline void OperatorSetProto::set_ir_build_metadata(const char* value, size_t size) {
  set_has_ir_build_metadata();
  if (ir_build_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_build_metadata_ = new ::std::string;
  }
  ir_build_metadata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:onnx.OperatorSetProto.ir_build_metadata)
}
inline ::std::string* OperatorSetProto::mutable_ir_build_metadata() {
  set_has_ir_build_metadata();
  if (ir_build_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ir_build_metadata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:onnx.OperatorSetProto.ir_build_metadata)
  return ir_build_metadata_;
}
inline ::std::string* OperatorSetProto::release_ir_build_metadata() {
  clear_has_ir_build_metadata();
  if (ir_build_metadata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ir_build_metadata_;
    ir_build_metadata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorSetProto::set_allocated_ir_build_metadata(::std::string* ir_build_metadata) {
  if (ir_build_metadata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ir_build_metadata_;
  }
  if (ir_build_metadata) {
    set_has_ir_build_metadata();
    ir_build_metadata_ = ir_build_metadata;
  } else {
    clear_has_ir_build_metadata();
    ir_build_metadata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:onnx.OperatorSetProto.ir_build_metadata)
}

// optional string domain = 4;
inline bool OperatorSetProto::has_domain() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OperatorSetProto::set_has_domain() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OperatorSetProto::clear_has_domain() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OperatorSetProto::clear_domain() {
  if (domain_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_->clear();
  }
  clear_has_domain();
}
inline const ::std::string& OperatorSetProto::domain() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorSetProto.domain)
  return *domain_;
}
inline void OperatorSetProto::set_domain(const ::std::string& value) {
  set_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_ = new ::std::string;
  }
  domain_->assign(value);
  // @@protoc_insertion_point(field_set:onnx.OperatorSetProto.domain)
}
inline void OperatorSetProto::set_domain(const char* value) {
  set_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_ = new ::std::string;
  }
  domain_->assign(value);
  // @@protoc_insertion_point(field_set_char:onnx.OperatorSetProto.domain)
}
inline void OperatorSetProto::set_domain(const char* value, size_t size) {
  set_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_ = new ::std::string;
  }
  domain_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:onnx.OperatorSetProto.domain)
}
inline ::std::string* OperatorSetProto::mutable_domain() {
  set_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:onnx.OperatorSetProto.domain)
  return domain_;
}
inline ::std::string* OperatorSetProto::release_domain() {
  clear_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = domain_;
    domain_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorSetProto::set_allocated_domain(::std::string* domain) {
  if (domain_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete domain_;
  }
  if (domain) {
    set_has_domain();
    domain_ = domain;
  } else {
    clear_has_domain();
    domain_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:onnx.OperatorSetProto.domain)
}

// optional int64 opset_version = 5;
inline bool OperatorSetProto::has_opset_version() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void OperatorSetProto::set_has_opset_version() {
  _has_bits_[0] |= 0x00000020u;
}
inline void OperatorSetProto::clear_has_opset_version() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void OperatorSetProto::clear_opset_version() {
  opset_version_ = GOOGLE_LONGLONG(0);
  clear_has_opset_version();
}
inline ::google::protobuf::int64 OperatorSetProto::opset_version() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorSetProto.opset_version)
  return opset_version_;
}
inline void OperatorSetProto::set_opset_version(::google::protobuf::int64 value) {
  set_has_opset_version();
  opset_version_ = value;
  // @@protoc_insertion_point(field_set:onnx.OperatorSetProto.opset_version)
}

// optional string doc_string = 6;
inline bool OperatorSetProto::has_doc_string() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void OperatorSetProto::set_has_doc_string() {
  _has_bits_[0] |= 0x00000040u;
}
inline void OperatorSetProto::clear_has_doc_string() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void OperatorSetProto::clear_doc_string() {
  if (doc_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_->clear();
  }
  clear_has_doc_string();
}
inline const ::std::string& OperatorSetProto::doc_string() const {
  // @@protoc_insertion_point(field_get:onnx.OperatorSetProto.doc_string)
  return *doc_string_;
}
inline void OperatorSetProto::set_doc_string(const ::std::string& value) {
  set_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_ = new ::std::string;
  }
  doc_string_->assign(value);
  // @@protoc_insertion_point(field_set:onnx.OperatorSetProto.doc_string)
}
inline void OperatorSetProto::set_doc_string(const char* value) {
  set_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_ = new ::std::string;
  }
  doc_string_->assign(value);
  // @@protoc_insertion_point(field_set_char:onnx.OperatorSetProto.doc_string)
}
inline void OperatorSetProto::set_doc_string(const char* value, size_t size) {
  set_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_ = new ::std::string;
  }
  doc_string_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:onnx.OperatorSetProto.doc_string)
}
inline ::std::string* OperatorSetProto::mutable_doc_string() {
  set_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    doc_string_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:onnx.OperatorSetProto.doc_string)
  return doc_string_;
}
inline ::std::string* OperatorSetProto::release_doc_string() {
  clear_has_doc_string();
  if (doc_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = doc_string_;
    doc_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorSetProto::set_allocated_doc_string(::std::string* doc_string) {
  if (doc_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete doc_string_;
  }
  if (doc_string) {
    set_has_doc_string();
    doc_string_ = doc_string;
  } else {
    clear_has_doc_string();
    doc_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:onnx.OperatorSetProto.doc_string)
}

// repeated .onnx.OperatorProto operator = 8;
inline int OperatorSetProto::operator__size() const {
  return operator__.size();
}
inline void OperatorSetProto::clear_operator_() {
  operator__.Clear();
}
inline const ::onnx::OperatorProto& OperatorSetProto::operator_(int index) const {
  // @@protoc_insertion_point(field_get:onnx.OperatorSetProto.operator)
  return operator__.Get(index);
}
inline ::onnx::OperatorProto* OperatorSetProto::mutable_operator_(int index) {
  // @@protoc_insertion_point(field_mutable:onnx.OperatorSetProto.operator)
  return operator__.Mutable(index);
}
inline ::onnx::OperatorProto* OperatorSetProto::add_operator_() {
  // @@protoc_insertion_point(field_add:onnx.OperatorSetProto.operator)
  return operator__.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::onnx::OperatorProto >&
OperatorSetProto::operator_() const {
  // @@protoc_insertion_point(field_list:onnx.OperatorSetProto.operator)
  return operator__;
}
inline ::google::protobuf::RepeatedPtrField< ::onnx::OperatorProto >*
OperatorSetProto::mutable_operator_() {
  // @@protoc_insertion_point(field_mutable_list:onnx.OperatorSetProto.operator)
  return &operator__;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace onnx

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::onnx::OperatorProto_OperatorStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::onnx::OperatorProto_OperatorStatus>() {
  return ::onnx::OperatorProto_OperatorStatus_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_onnx_2doperators_5fONNX_5fNAMESPACE_2dml_2eproto__INCLUDED
