package:
  name: morphsnakes 
  version: "0.0.11"

source:
  git_rev: 0.0.11
  git_url: .
#  fn: imtools-0.0.17.tar.gz
#  url: https://pypi.python.org/packages/source/i/imtools/imtools-0.0.17.tar.gz
#  md5: 2c88dfda63b4b8dc2f849e4e0218f7fb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - imtools = imtools:main
    #
    # Would create an entry point called imtools that calls imtools.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - mock
    - nose

  run:
    - python
    - numpy
    - scipy

test:
  # Python imports
  imports:
    - morphsnakes 

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/imtools
  license: BSD License
  summary: '3D data processing toolbox'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
