language: python
services:
  - docker
sudo: true
python:
  - 3.5
  - 3.6
install:
  - bash ci/install.sh
script:
  - bash ci/script.sh
after_success:
  - bash ci/after_success.sh
before_deploy:
  - bash ci/before_deploy.sh
deploy:
  provider: pypi
  user: akretion
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: BReJB0dEdGdTPnKHE6WVvZ9AuJCmq3Tc89DWTrAS1rOcrNU+oJ+rfjVG//Kc1isZjvq+kiBfj6IUO9OP1Y1krDSjAzRGQJa/ex0Yjh302PuoUvPASoyGWBXm2w6ZvzhZhBmGW4dSTeNg9UyUQHQQl0W00hOMcH1WI7kgJevntM0=
notifications:
  email: false
