
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-11T10:48:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "61c8d2ffb93f5743fd2be2ef82ddf32d2f5d5e8e",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
