
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "92778d208193e6afa2d13abc7797a6dc594e2d20",
 "version": "0.5.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
