
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6bcda77211a5f32abf8bd8046fc6f8df952689c7",
 "version": "0.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
