
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-17T14:00:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6869655818cdc03afa4f5946c6391bf7cca7aae0",
 "version": "2.13.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
