
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-07T22:15:48+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "c9395eb427dc1bddb1dcb49816cbc0bec83d9bbc",
 "version": "2.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
