##############################################################################
# Copyright (c) 2017 akhil.batra@research.iiit.ac.in and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

swagger: '2.0'
info:
  title: QTIP-API
  version: "1.0"
consumes:
  - application/json
produces:
  - application/json
paths:
  /qpis:
    get:
      summary: List all QPIs
      operationId: qtip.api.controllers.qpi.list_qpis
      tags:
        - QPI
        - Standalone
        - Agent
      responses:
        200:
          description: A list of QPIs
          schema:
            items:
              $ref: '#/definitions/QPIs'
        501:
          description: Resource not implemented
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /qpis/{name}:
    get:
      summary: Get a QPI
      operationId: qtip.api.controllers.qpi.get_qpi
      tags:
        - QPI
        - Standalone
        - Agent
      parameters:
        - name: name
          in: path
          description: QPI name
          required: true
          type: string
      responses:
        200:
          description: QPI information
          schema:
            $ref: '#/definitions/QPI'
        404:
          description: QPI not found
          schema:
            $ref: '#/definitions/Error'
        501:
          description: Resource not implemented
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  QPI:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      description:
        type: string
      formula:
        type: string
      sections:
        type: array
        items:
          type: object
  QPIs:
    type: object
    required:
      - qpis
    properties:
      qpis:
        type: array
        items:
          type: string
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      title:
        type: string
      detail:
        type: string
      type:
        type: string