# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pretix.base.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0088_auto_20180328_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesales', to='pretixbase.Event')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='pretixbase.TaxRule')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.AlterModelOptions(
            name='quota',
            options={'ordering': ('name',), 'verbose_name': 'Quota', 'verbose_name_plural': 'Quotas'},
        ),
        migrations.AddField(
            model_name='team',
            name='can_change_wholesales',
            field=models.BooleanField(default=False, verbose_name='Can change wholesales'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_view_wholesales',
            field=models.BooleanField(default=False, verbose_name='Can view wholesales'),
        ),
        migrations.AlterField(
            model_name='orderfee',
            name='fee_type',
            field=models.CharField(choices=[('payment', 'Payment fee'), ('shipping', 'Shipping fee'), ('service', 'Service fee'), ('other', 'Other fees'), ('giftcard', 'Gift card')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('de-informal', 'German (informal)')], default='en', max_length=50, verbose_name='Language'),
        ),
    ]
