# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0092_remove_order_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wholesale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.WholesaleAccounts', verbose_name='Wholesale Account'),
        ),
    ]
