
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-13T10:06:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ada1ea82e41d20884cb13a8099613d662c34415c",
 "version": "0.12.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
