# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_time__',
    '__build_status__'
]

__version__ = '0.1.4.dev1+g0ab13cc8'
__version_short__ = '0.1.4'
__version_long__ = '0.1.4-1-g0ab13cc8'
__version_post__ = '1'
__version_commit__ = '0ab13cc8'
__version_date__ = '2018-05-04 09:08:33 -0400'
__version_dirty__ = False
__build_date__ = '2018-05-04'
__build_time__ = '09:09:13.160548'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
