
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-02T19:11:48+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "ec5eb0bff58bd4104bba396fdeadcb5a16a2236c",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
