
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-19T13:37:52-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "bf4c9ed9e02f4164f2875502a11783cb648c8cb5",
 "version": "v0.2.4.post.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
