
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-31T13:58:49-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5a16286725a58564fb791c1c5864f4f3d0e76e7",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
