STATE_PROV_NORMALIZATION = {'New Mexico': 'New Mexico',
                            'Oaxaca': 'Oaxaca',
                            'WI': 'Wisconsin',
                            'Querétaro': 'Querétaro',
                            'Henan': 'Henan',
                            None: None,
                            'Thessalia': 'Thessalia',
                            'ID': 'Idaho',
                            'Shanxi': 'Shaanxi',
                            'WA': 'Western Australia',
                            'DE': 'Delaware',
                            'Tôkyô': 'Tokyo',
                            'Missouri': 'Missouri',
                            'TA': 'Center District',
                            'New Jersey': 'New Jersey',
                            'Caldas': 'Caldas',
                            'Massachusetts': 'Massachusetts',
                            'Diyarbakir': 'Diyarbakir',
                            'Virginia': 'Virginia',
                            'Puebla': 'Puebla',
                            'Taipei': 'Taipei City',
                            'Shaanxi': 'Shaanxi',
                            'Aguascalientes': 'Aguascalientes',
                            'Chihuahua': 'Chihuahua', 'Québec': 'Québec',
                            'Chongqing': 'Chongqing',
                            'NM': 'New Mexico',
                            'South Carolina': 'South Carolina',
                            'Maharashtra': 'Maharashtra',
                            'Noord-Brabant': 'Noord-Brabant',
                            'RM': 'Santiago Metropolitan Region',
                            'Eskisehir': 'Eskişehir Province',
                            '21': 'Shanghai Shi',
                            'P': 'Pichincha',
                            'São Paulo': 'São Paulo',
                            '00': None,
                            'NL': 'Newfoundland and Labrador',
                            'Z': 'Center District',
                            'Southern': 'Center District',
                            'Jalisco': 'Jalisco',
                            'Groningen': 'Groningen',
                            'Samsun': 'Samsun',
                            'Taichung': 'Taichung',
                            'Limburg': 'Limburg',
                            'GUA': 'Guanajuato',
                            '34': 'Sivas',
                            'Maine': 'Maine',
                            'Illinois': 'Illinois',
                            'NE': 'Nebraska',
                            'Yucatán': 'Yucatán',
                            'Lubelskie': 'lubelskie',
                            'HaZafon (Northern)': 'Haifa District',
                            'RS': 'Rio Grande do Sul',
                            'SP': 'São Paulo',
                            'Hercegova?ko-neretvanski kanton': 'Federation of Bosnia and Herzegovina',
                            'Montana': 'Montana',
                            'Adana': 'Adana', 'CO': 'Colorado',
                            '44': 'Xinjiang Weiwuerzizhiqu',
                            'Northern Territory': 'Northern Territory', 'Maryland': 'Maryland', 'WY': 'Wyoming',
                            'Idaho': 'Idaho', 'Mexico': 'Estado de México', 'Oregon': 'Oregon',
                            'Nord-Trøndelag': 'Nord-Trøndelag', 'BC': 'British Columbia', 'AST': 'Akmola Province',
                            'Kentucky': 'Kentucky', 'M': 'Tel Aviv District',
                            'Distrito Nacional (Santo Domingo)': 'Distrito Nacional (Santo Domingo)',
                            'Saitama': 'Saitama Prefecture', 'MD': 'Maryland', 'OAX': 'Oaxaca',
                            'Haifa': 'North District', 'DIF': 'Mexico City', 'Chiayi': 'Chiayi',
                            'South Dakota': 'South Dakota', 'CT': 'Connecticut', 'MA': 'Massachusetts',
                            'Sonora': 'Sonora', 'Paraná': 'Paraná', 'Yukon Territory': 'Yukon Territory',
                            'New Hampshire': 'New Hampshire', 'Mississippi': 'Mississippi', 'Hawaii': 'Hawaii',
                            '22': 'Hunan Sheng', 'Edirne': 'Edirne', 'Colima': 'Colima', 'Chiba': 'Chiba',
                            'Nebraska': 'Nebraska', 'Antioquia': 'Antioquia', 'AB': 'Alberta', 'Michoacán': 'Michoacán',
                            'TAS': 'Tasmania', 'Sinaloa': 'Sinaloa', 'Minnesota': 'Minnesota', 'CHH': 'Chihuahua',
                            'Zhejiang': 'Zhejiang', 'Alberta': 'Alberta', 'AZ': 'Arizona', 'PA': 'Pennsylvania',
                            'Istanbul': 'Sivas', 'OK': 'Oklahoma', 'Distrito Federal': 'Ciudad de México',
                            'Louisiana': 'Louisiana', 'Antalya': 'Antalya', 'Tabasco': 'Tabasco', 'ME': 'Maine',
                            'LI': 'Limburg', 'Yunnan': 'Yunnan', 'Tainan': 'Tainan', 'AK': 'Alaska', 'Sinop': 'Sinop',
                            'UT': 'Utah', 'AR': 'Arkansas', 'Washington': 'Washington', 'Pennsylvania': 'Pennsylvania',
                            'Guayas': 'Guayas', 'Chiapas': 'Chiapas', 'Durango': 'Durango', 'MI': 'Michigan',
                            'Sichuan': 'Sichuan', 'Kars': 'Kars', 'Michigan': 'Michigan', 'Guanajuato': 'Guanajuato',
                            'North Dakota': 'North Dakota', 'Queensland': 'Queensland', 'Arkansas': 'Arkansas',
                            'Primorsko-goranska županija': 'Primorsko-goranska županija', 'DC': 'District of Columbia',
                            'Wyoming': 'Wyoming', 'Rhône': 'Auvergne-Rhône-Alpes', 'Nevada': 'Nevada',
                            'Quintana Roo': 'Quintana Roo', 'ND': 'North Dakota', 'West Virginia': 'West Virginia',
                            'Izmir': 'İzmir', 'Ha Noi': 'Hà Nội', 'SE': 'Sergipe', 'Hidalgo': 'Hidalgo',
                            'Ontario': 'Ontario', 'ZAC': 'Zacatecas', 'Tamaulipas': 'Tamaulipas',
                            'Connecticut': 'Connecticut', 'MIC': 'Michoacán', 'JM': 'Center District',
                            'Hong Kong (Xianggang)': 'Hong Kong (Xianggang)', 'Cundinamarca': 'Cundinamarca',
                            'Changhua': 'Changhua', 'Rhode Island': 'Rhode Island', 'Jilin': 'Jilin Sheng',
                            'NV': 'Nevada', 'AL': 'Alabama', 'Guangdong': 'Guangdong Sheng',
                            'Shanghai': 'Jiangsu Sheng', 'Shandong': 'Shandong', 'Florida': 'Florida', 'ON': 'Ontario',
                            'Zacatecas': 'Zacatecas', 'VA': 'Virginia', 'Utah': 'Utah', 'Tasmania': 'Tasmania',
                            'Central Singapore': 'Central Singapore', 'Alaska': 'Alaska', 'BW': 'Baden-Württemberg',
                            '13': 'Shandong Sheng', 'NH': 'New Hampshire', 'GA': 'Georgia', 'Wisconsin': 'Wisconsin',
                            'Nigde': 'Nigde', 'MO': 'Missouri', 'Bursa': 'Bursa', 'AM': 'Amazonas',
                            'District of Columbia': 'District of Columbia', 'Hessen': 'Hessen', 'SD': 'South Dakota',
                            'Praha 8': 'Prague', 'NS': 'Nova Scotia', 'Indiana': 'Indiana', 'PR': 'PR',
                            'Kansas': 'Kansas', 'IN': 'Indiana', 'Saskatchewan': 'Saskatchewan', 'Kayseri': 'Kayseri',
                            'HaDarom (Southern)': 'South District', 'Oromiya': 'Oromiya',
                            'Armed Forces - Pacific': 'Armed Forces - Pacific', '11': 'Gansu Sheng', 'KS': 'Kansas',
                            'San Luis Potosí': 'San Luis Potosi', 'Glarus': 'Canton of Glarus', 'Arizona': 'Arizona',
                            'Çorum': 'Çorum', 'Kocaeli': 'Kocaeli', 'New York': 'New York', 'FL': 'Florida',
                            'Texas': 'Texas', 'Kronobergs län': 'Kronobergs län', 'MOR': 'Morelos',
                            'Puerto Rico': 'San Juan', 'MN': 'Minnesota', 'Abu Z¸aby (Abu Dhabi)': 'Abu Dhabi',
                            'USA': None, 'CA': 'California', 'Aydin': 'Aydin',
                            'Macau (Aomen)': 'Macau (Aomen)', 'MT': 'Montana', 'NC': 'North Carolina',
                            'Western Australia': 'Western Australia', 'ANT': 'Antioquia',
                            'Rio Grande do Sul': 'Rio Grande do Sul', 'BI': 'Bío Bío Region', 'Ohio': 'Ohio',
                            'Región Metropolitana de Santiago': 'Región Metropolitana', 'Meknès': 'Meknes-Tafilalet',
                            'ENG': 'England', 'Jiangsu': 'Jiangsu', 'OR': 'Oregon', 'D': 'Haifa District',
                            'England': 'England', 'WV': 'West Virginia', 'HI': 'Hawaii', 'BA': 'Bahia',
                            'Asunción': 'Asunción', 'Victoria': 'Victoria', 'West Bengal': 'West Bengal',
                            '46': 'Shandong Sheng', 'KY': 'Kentucky', 'HA': 'Center District',
                            'MEX': 'Ciudad de México', 'QC': 'Québec', 'SC': 'South Carolina', 'NLE': 'Nuevo León',
                            'TX': 'Texas', 'HaMerkaz (Central)': 'Haifa District', 'Liaoning': 'Liaoning',
                            'Veracruz': 'Veracruz', 'CMD': 'CMD', 'California': 'California',
                            'Loire': 'Auvergne-Rhône-Alpes', 'Santa Catarina': 'Santa Catarina',
                            'Armed Forces - Americas': 'Armed Forces - Americas', 'Tennessee': 'Tennessee',
                            'JAL': 'Jalisco', 'Isparta': 'Isparta', 'VIC': 'Victoria', 'Iowa': 'Iowa',
                            'TN': 'Tennessee', 'RI': 'Rhode Island', '52': 'Shandong Sheng',
                            'North Carolina': 'North Carolina', 'South Australia': 'South Australia',
                            'Vermont': 'Vermont', 'Delhi': 'Delhi', 'PB': 'Punjab', 'Georgia': 'Georgia',
                            'IL': 'Illinois', 'BCN': 'Baja California', 'New South Wales': 'New South Wales',
                            'Nuevo León': 'Nuevo León', 'Ankara': 'Ankara', 'NJ': 'New Jersey', 'OH': 'Ohio',
                            'Santo Domingo': 'Distrito Nacional', 'Colorado': 'Colorado', 'MS': 'Mississippi',
                            'Tel-Aviv': 'Center District', 'Fujian': 'Fujian', 'Alabama': 'Alabama', 'LA': 'Louisiana',
                            'Beijing': 'Beijing Shi', 'Guam': 'Guam', 'Morelos': 'Morelos',
                            'South Denmark': 'South Denmark', 'Coahuila': 'Coahuila de Zaragoza', 'Qinghai': 'Qinghai',
                            'VER': 'Veracruz', 'Bolzano': 'Bolzano', 'Yerushalayim': 'Jerusalem District',
                            'NY': 'New York', 'Distrito Capital de Bogotá': 'Bogota',
                            'Baja California': 'Baja California', 'Hubei': 'Hubei', 'Gansu': 'Gansu Sheng',
                            'British Columbia': 'British Columbia', 'Delaware': 'Delaware', 'Oklahoma': 'Oklahoma',
                            'NB': 'New Brunswick'}
