# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauge',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
    ]
