
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-20T10:46:17-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "308b906f6f0c9aa0df3e99d101583c7a884b72da",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
