
# Generated by Django 1.10.6 on 2017-03-23 13:45


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0448\u0430\u0431\u043b\u043e\u043d\u0430')),
                ('template', models.CharField(editable=False, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 HTML \u0448\u0430\u0431\u043b\u043e\u043d\u0430. \u0421\u043e\u0437\u0434\u0430\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438, \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u0438\u043c\u0435\u043d\u0438 \u0415\u0441\u043b\u0438 \u043e\u0434\u043d\u043e\u0438\u043c\u0435\u043d\u043d\u043e\u0433\u043e \u0448\u0430\u0431\u043b\u043e\u043d\u0430 \u043d\u0435\u0442\u0443 \u0432 \u043f\u0430\u043f\u043a\u0435, \u043e\u043d \u0431\u0443\u0434\u0435\u0442 \u0441\u043e\u0437\u0434\u0430\u043d \u0430\u0432\u0442\u043e\u043c\u0430\u0447\u0435\u0441\u043a\u0438', max_length=255, verbose_name='HTML \u0448\u0430\u0431\u043b\u043e\u043d')),
                ('subject', models.CharField(default='no-reply', help_text='\u041d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435, \u043f\u043e-\u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u0441\u0442\u043e\u0438\u0442 no-reply', max_length=255, verbose_name='\u0422\u0435\u043c\u0430 \u043f\u0438\u0441\u044c\u043c\u0430')),
                ('from_email', models.CharField(default='octo@octoberweb.ru', help_text='\u041d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435, \u043f\u043e-\u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u0441\u0442\u043e\u0438\u0442 no-reply', max_length=255, verbose_name='\u041e\u0442 \u043a\u043e\u0433\u043e \u043f\u0438\u0441\u044c\u043c\u043e')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('footer', models.TextField(blank=True, verbose_name='\u0424\u0443\u0442\u0435\u0440')),
                ('admin_url', models.CharField(blank=True, max_length=500, verbose_name='URL \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435')),
                ('subscribers', models.ManyToManyField(related_name='mail_forms', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0428\u0430\u0431\u043b\u043e\u043d \u0434\u043b\u044f \u0430\u0434\u043c\u0438\u043d\u0430',
                'verbose_name_plural': '\u0428\u0430\u0431\u043b\u043e\u043d\u044b \u0434\u043b\u044f \u0430\u0434\u043c\u0438\u043d\u0430',
            },
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0448\u0430\u0431\u043b\u043e\u043d\u0430')),
                ('template', models.CharField(editable=False, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 HTML \u0448\u0430\u0431\u043b\u043e\u043d\u0430. \u0421\u043e\u0437\u0434\u0430\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438, \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u0438\u043c\u0435\u043d\u0438 \u0415\u0441\u043b\u0438 \u043e\u0434\u043d\u043e\u0438\u043c\u0435\u043d\u043d\u043e\u0433\u043e \u0448\u0430\u0431\u043b\u043e\u043d\u0430 \u043d\u0435\u0442\u0443 \u0432 \u043f\u0430\u043f\u043a\u0435, \u043e\u043d \u0431\u0443\u0434\u0435\u0442 \u0441\u043e\u0437\u0434\u0430\u043d \u0430\u0432\u0442\u043e\u043c\u0430\u0447\u0435\u0441\u043a\u0438', max_length=255, verbose_name='HTML \u0448\u0430\u0431\u043b\u043e\u043d')),
                ('subject', models.CharField(default='no-reply', help_text='\u041d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435, \u043f\u043e-\u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u0441\u0442\u043e\u0438\u0442 no-reply', max_length=255, verbose_name='\u0422\u0435\u043c\u0430 \u043f\u0438\u0441\u044c\u043c\u0430')),
                ('from_email', models.CharField(default='octo@octoberweb.ru', help_text='\u041d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435, \u043f\u043e-\u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u0441\u0442\u043e\u0438\u0442 no-reply', max_length=255, verbose_name='\u041e\u0442 \u043a\u043e\u0433\u043e \u043f\u0438\u0441\u044c\u043c\u043e')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField(blank=True, verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('footer', models.TextField(blank=True, verbose_name='\u0424\u0443\u0442\u0435\u0440')),
                ('admin_template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.AdminTemplate', verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d \u0434\u043b\u044f \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0428\u0430\u0431\u043b\u043e\u043d \u0434\u043b\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u0428\u0430\u0431\u043b\u043e\u043d\u044b \u0434\u043b\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f',
            },
        ),
    ]
