package:
  name: libndtypes
  version: 0.2.0dev3

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY', 'NA') }}_{{ environ.get('GIT_BUILD_STR', 'NA') }}

test:
  skip: True  # tests are in build.sh

about:
  home: https://github.com/plures/
  license: BSD 3-clause

source:
  git_url: ../../
