# coding: utf-8

"""
    MLServer
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ExecuteRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, code=None, input_parameters=None, output_parameters=None):
        """
        ExecuteRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'code': 'str',
            'input_parameters': 'list[SessionsidexecuteInputParameters]',
            'output_parameters': 'list[str]'
        }

        self.attribute_map = {
            'code': 'code',
            'input_parameters': 'inputParameters',
            'output_parameters': 'outputParameters'
        }

        self._code = code
        self._input_parameters = input_parameters
        self._output_parameters = output_parameters

    @property
    def code(self):
        """
        Gets the code of this ExecuteRequest.
        code to execute. **<font color = 'red'>Required</font>**

        :return: The code of this ExecuteRequest.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this ExecuteRequest.
        code to execute. **<font color = 'red'>Required</font>**

        :param code: The code of this ExecuteRequest.
        :type: str
        """

        self._code = code

    @property
    def input_parameters(self):
        """
        Gets the input_parameters of this ExecuteRequest.
        Input parameters for the execution. **Optional**

        :return: The input_parameters of this ExecuteRequest.
        :rtype: list[SessionsidexecuteInputParameters]
        """
        return self._input_parameters

    @input_parameters.setter
    def input_parameters(self, input_parameters):
        """
        Sets the input_parameters of this ExecuteRequest.
        Input parameters for the execution. **Optional**

        :param input_parameters: The input_parameters of this ExecuteRequest.
        :type: list[SessionsidexecuteInputParameters]
        """

        self._input_parameters = input_parameters

    @property
    def output_parameters(self):
        """
        Gets the output_parameters of this ExecuteRequest.
        Output parameters for the execution. **Optional**

        :return: The output_parameters of this ExecuteRequest.
        :rtype: list[str]
        """
        return self._output_parameters

    @output_parameters.setter
    def output_parameters(self, output_parameters):
        """
        Sets the output_parameters of this ExecuteRequest.
        Output parameters for the execution. **Optional**

        :param output_parameters: The output_parameters of this ExecuteRequest.
        :type: list[str]
        """

        self._output_parameters = output_parameters

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ExecuteRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
