# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_time__',
    '__build_status__'
]

__version__ = '0.1.7.dev1+gc4c3acd8'
__version_short__ = '0.1.7'
__version_long__ = '0.1.7-1-gc4c3acd8'
__version_post__ = '1'
__version_commit__ = 'c4c3acd8'
__version_date__ = '2018-05-15 11:35:41 -0400'
__version_dirty__ = False
__build_date__ = '2018-05-15'
__build_time__ = '11:36:38.590115'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
