
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-16T21:52:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "216d3a71346344ab8902f894e02d81be7f69cb20",
 "version": "0.5.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
