language: python
python:
- '3.6'
install:
- pip install .
script: python -m unittest discover
deploy:
  provider: pypi
  username: dexter2206
  password:
    secure: o9pOOFvU+uJfJsM5HJAirsRRcsIpN6Rw2lCVv1qQ8HxwbBEakFE5cvZf4c58lccKMf4eCk+pWzkkbFOwxcKz0TWlsZZEgKICEG40I9nItiUlN2xwHDqzsgSjJc5n7WBEZBXCmfi7dNDBdU9smybnja1ApjZiv86FfHIUU2/Xwxsk+kjRweDttAp8+Ksd+AlC85Bg9XGBQxIeGstD2OpqCOgR+kqbTN8wntrti9zIGETefm+bbc1uSgbZ39TJp6SNoi2ZD9sPXpKX8ajlqVJ+FP4RcyY8wPLP0MVq8t3iOhw/lPYE3hTKR7qMkPcBeg8foYtwnk3j8cL8S//HMjD1Wk05W/9EsHXwuX+DurUF+KLgdvOo9hV4pZ7xW3UwwrT4CjlUD9UFPcj7tq2dKcUm0T4rKke+r+UZN7L+i/Shs2WL8KF5ZTqzb30u/WQ9TPddU5v/UfKJbJzoRGsuxV/FM1HsuNRom3fe3QTM8D2TPcRUFxiwuNuYIeRXmdRaSWdKqoqu3lTw5lnH+4pL8sd/CHZkv8wiPR30XCDwFDFjY0EiCUL6Pkfo+C23cX4JsorW8aCHR/w8vBCngpTS3lfMlmc6SNdArb4LLr/4uz+6OdT+j0rg2S/bnSsPaZj8oUZfEG1UdzdeZ14+vF5sRU5ewVS234uam/lgUo7o34K6j0E=
  on:
    tags: true
