
'''
This file is automatically generated; Do not edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.16.0.post1',
    'branch_nick': '(detached',
    'revision_id': '6e005af55326dd42e99cb8f6a96b72e2ac629e71',
    'revno': 6567
}
