---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: false
    ingress.kubernetes.io/app-root: /
spec:
  rules:
  - host: {{ settings.provision.domain }}
    http:
      paths:
      - path: /grafana
        backend:
          serviceName: metrics-grafana-service
          servicePort: 80