
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-17T16:43:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c34835be9fd9e1476230e2999e4fcf2e5171bee",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
