
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f33de9ead7e6123f574f08e43d6aedfc24efde4c",
 "version": "0.5.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
