# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 21:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20170419_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
