
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bc6783d938ddc9c01adc1021145ace112365beec",
 "version": "2.3.2-001"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
