language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies

before_install:
  - sudo apt-get update
  - sudo apt-get install python-enchant

install:
  - "pip install -U pip"
  - "pip install -r requirements.txt"
  - "pip install ."

# command to run tests
script:
  - pytest

# safelist
branches:
  only:
  - master
