
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-28T21:43:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa35a96169e2418429a53a3acc8f5126a5d43fe9",
 "version": "v0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
