
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-11T18:13:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ef4e547ddd01ae6fd81fbccd345c9afbb06188d",
 "version": "0.2.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
