
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "dc7f08ffd5696a37d6028d1d46c9163e7994bc6f",
 "version": "v0.1.1-alpha.post.dev47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
