version: '2'
services:
  elasticsearch1:
    cap_add:
      - IPC_LOCK
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{es_version}}"
    ports:
      - {{http_port}}:{{http_port}}
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - {{es_data_dir}}:/usr/share/elasticsearch/data
      - {{es_log_dir}}:/var/log/elasticsearch
{%- for host_path, docker_path in mounts.items() %}
      - {{host_path}}:{{docker_path}}
{%- endfor %}
