# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 16, 17, 39, 12, 385808, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 5, 16, 17, 39, 15, 855568, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
