# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 23:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170516_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoccurrence',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
