# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-12 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventoccurrence_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Access'),
        ),
    ]
