# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0095_opening_closing_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening_closing_balance',
            old_name='data',
            new_name='date',
        ),
    ]
