
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-14T11:03:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2467d74f0e292467cb0f26e1120157105f4be651",
 "version": "0.2.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
