# -*- coding: utf-8 -*-
#
# THIS FILE IS AUTOGENERATED FROM SETUP.PY. DO NOT EDIT.
#
public_version   = "0.0.5"
local_version    = "0.0.5+20180509T192728Z.f49c7787d4df5febddde6ac829af93932d9761ce"
sem_version      = "0.0.5+buildtime.20180509T192728Z.git.f49c7787d4df5febddde6ac829af93932d9761ce"

release_version  = "0.0.5"
__version__      = "0.0.5"
release          = True

vcs_tag          = "f49c7787d4df5febddde6ac829af93932d9761ce"
vcs_clean        = True
build_time_posix = 1525894048
build_time_iso   = "20180509T192728Z"
