language: python

jobs:
  fast_finish: true
  include:
  - python: 2.7
  - python: &latest_py3 3.6
  - os: osx
    language: generic
    python: *latest_py3
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: aDqlVdm6FZ8pqLkoDRR2LH3TEz7pBvKH2HhOlSy7OEmopN/36ncql/KvfE0ccpaOES9Xm31a51bUfNjcwb1HVKjfW544C+IoSHctkG1rI5bp3q4rW+4RbQcBZVHUUKR9yQf9ZyikEmoYXi3g+JKcOf9rj+v/32PAfUDzSpFbWik=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

cache: pip

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis-macos; fi

install:
- pip install tox tox-venv

script: tox
