language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

install:
    - pip install -U setuptools==33.1.1
    - pip install coveralls coverage
    - pip install zc.buildout
    - pip install -U six==1.10.0
    - buildout bootstrap
    - buildout

script:
    - coverage run bin/test -v1
after_success:
    - coverage combine
    - coveralls

notifications:
    email: false

cache:
  pip: true
  directories:
    - eggs/
