
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-17T22:36:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1c6e71633bfb3f600c0694c83004a55a99a757c",
 "version": "v0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
