
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-12T14:52:20+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "aafb39d10376ec58d543f7a3a7a820c916fd7358",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
