
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-26T21:43:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e36af1f7577aa40a8610da359b849e618aaf414",
 "version": "1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
