
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-24T11:24:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3783586fe23064a004058f81c8f5a2044ed4132",
 "version": "0.35.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
