
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-04T20:42:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aada4a3626ac436075e6946b9f5c6d23f16cfc5a",
 "version": "v0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
