
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-19T07:54:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "38d65a9f2f16b7007166919f78084dc6bf014f20",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
