
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-01T17:51:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b977ecc51c54b75b76aef9da87e92d7a47725943",
 "version": "2.2.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
