
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftANDORrightNOTLPAREN RPAREN FIELD AND OR NOTexpression : expression AND expressionexpression : expression OR expressionexpression : NOT expressionexpression : LPAREN expression RPARENexpression : FIELD'
    
_lr_action_items = {'$end':([1,3,8,9,10,11,],[0,-5,-3,-2,-1,-4,]),'LPAREN':([0,2,4,5,6,],[2,2,2,2,2,]),'OR':([1,3,7,8,9,10,11,],[5,-5,5,-3,-2,-1,-4,]),'FIELD':([0,2,4,5,6,],[3,3,3,3,3,]),'RPAREN':([3,7,8,9,10,11,],[-5,11,-3,-2,-1,-4,]),'NOT':([0,2,4,5,6,],[4,4,4,4,4,]),'AND':([1,3,7,8,9,10,11,],[6,-5,6,-3,-2,-1,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,4,5,6,],[1,7,8,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression AND expression','expression',3,'p_expression_and','parser.py',15),
  ('expression -> expression OR expression','expression',3,'p_expression_or','parser.py',20),
  ('expression -> NOT expression','expression',2,'p_expression_not','parser.py',25),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_paren','parser.py',30),
  ('expression -> FIELD','expression',1,'p_expression_field','parser.py',35),
]
