
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-25T12:43:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4421ffb33c889f0e52f673625b434d25a462a49c",
 "version": "0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
