
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-15T19:27:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "95b4d545ad2f05c40ea86541fdbba5978a7226cf",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
