# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0089_auto_20180418_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleaccount',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='wholesaleaccount',
            name='address2',
        ),
        migrations.AddField(
            model_name='wholesaleaccount',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wholesaleaccount',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wholesaleaccount',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wholesaleaccount',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wholesaleaccount',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wholesaleaccount',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wholesaleaccount',
            name='tax',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
