# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0091_auto_20180510_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wholesale',
        ),
    ]
