
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-17T13:01:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e493fbeb013a49b3c116f3b41834169ab823fe5",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
