
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-25T15:55:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f3006da24affc63752c1fcb261152105fe160ec",
 "version": "4.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
