- job:
    name: oslo.messaging-tox-py27-func-amqp1
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-amqp1

- job:
    name: oslo.messaging-tox-py27-func-kafka
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-kafka
      bindep_profile: kafka

- job:
    name: oslo.messaging-tox-py27-func-rabbit
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-rabbit
      bindep_profile: rabbit

- job:
    name: oslo.messaging-tox-py35-func-amqp1
    parent: openstack-tox-py35
    vars:
      tox_envlist: py35-func-amqp1

- job:
    name: oslo.messaging-tox-py35-func-rabbit
    parent: openstack-tox-py35
    vars:
      tox_envlist: py35-func-rabbit
      bindep_profile: rabbit

- job:
    name: oslo.messaging-src-dsvm-full-rabbit-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-rabbit-default/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-rabbit-default/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-amqp1-dual-centos-7
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-amqp1-dual-centos-7/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-amqp1-dual-centos-7/post.yaml
    timeout: 10800
    nodeset: legacy-centos-7
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-amqp1
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-amqp1-hybrid
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-amqp1-hybrid/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-amqp1-hybrid/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-amqp1
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-kafka-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-kafka-default/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-kafka-default/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-kafka
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-kafka-default-centos-7
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-kafka-default-centos-7/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-kafka-default-centos-7/post.yaml
    timeout: 10800
    nodeset: legacy-centos-7
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-kafka
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-grenade-dsvm
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-grenade-dsvm/run.yaml
    post-run: playbooks/oslo.messaging-src-grenade-dsvm/post.yaml
    timeout: 10800
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/oslo.messaging
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$

- job:
    name: oslo.messaging-src-grenade-dsvm-multinode
    parent: legacy-dsvm-base-multinode
    run: playbooks/oslo.messaging-src-grenade-dsvm-multinode/run.yaml
    post-run: playbooks/oslo.messaging-src-grenade-dsvm-multinode/post.yaml
    timeout: 10800
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/oslo.messaging
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    nodeset: legacy-ubuntu-xenial-2-node

- job:
    name: oslo.messaging-telemetry-dsvm-integration-amqp1
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-amqp1/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-amqp1/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-amqp1
      - openstack/oslo.messaging
      - openstack/panko
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- job:
    name: oslo.messaging-telemetry-dsvm-integration-kafka
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-kafka/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-kafka/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-kafka
      - openstack/oslo.messaging
      - openstack/panko
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- job:
    name: oslo.messaging-telemetry-dsvm-integration-rabbit
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-rabbit/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-rabbit/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/oslo.messaging
      - openstack/panko
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- job:
    name: oslo.messaging-tempest-neutron-dsvm-src-rabbit-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-rabbit-default/run.yaml
    post-run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-rabbit-default/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/tempest

- job:
    name: oslo.messaging-tempest-neutron-dsvm-src-amqp1-hybrid
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-amqp1-hybrid/run.yaml
    post-run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-amqp1-hybrid/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-amqp1
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/tempest

- job:
    name: oslo.messaging-tempest-neutron-dsvm-src-kafka-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-kafka-default/run.yaml
    post-run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-kafka-default/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-kafka
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/tempest


- project:
    check:
      jobs:
        - oslo.messaging-tox-py27-func-amqp1:
            voting: false
        - oslo.messaging-tox-py27-func-kafka:
            voting: false
        - oslo.messaging-tox-py27-func-rabbit
        - oslo.messaging-tox-py35-func-amqp1:
            voting: false
        - oslo.messaging-tox-py35-func-rabbit:
            voting: false

        - oslo.messaging-src-dsvm-full-rabbit-default
        - oslo.messaging-src-dsvm-full-amqp1-hybrid:
            voting: false
            branches: ^(?!stable/ocata).*$
        - oslo.messaging-src-dsvm-full-amqp1-dual-centos-7:
            voting: false
            branches: ^(?!stable/ocata).*$
        - oslo.messaging-src-dsvm-full-kafka-default-centos-7:
            voting: false
        - oslo.messaging-src-dsvm-full-kafka-default:
            voting: false

        - oslo.messaging-src-grenade-dsvm:
            voting: false
        - oslo.messaging-src-grenade-dsvm-multinode:
            voting: false

        - oslo.messaging-telemetry-dsvm-integration-rabbit
        - oslo.messaging-telemetry-dsvm-integration-amqp1:
            voting: false
        - oslo.messaging-telemetry-dsvm-integration-kafka:
            voting: false

        - oslo.messaging-tempest-neutron-dsvm-src-rabbit-default
        - oslo.messaging-tempest-neutron-dsvm-src-amqp1-hybrid:
            voting: false
            branches: ^(?!stable/ocata).*$
        - oslo.messaging-tempest-neutron-dsvm-src-kafka-default:
            voting: false

        - openstack-tox-lower-constraints
    gate:
      jobs:
        - oslo.messaging-tox-py27-func-rabbit
        - oslo.messaging-telemetry-dsvm-integration-rabbit
        - oslo.messaging-src-dsvm-full-rabbit-default
        - oslo.messaging-tempest-neutron-dsvm-src-rabbit-default




        - openstack-tox-lower-constraints
