# coding: utf-8

"""
    stylelens-feature

    This is a API document for Object Detection on fashion items\"

    OpenAPI spec version: 0.0.1
    Contact: devops@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import stylelens_feature
from stylelens_feature.rest import ApiException
from stylelens_feature.models.boxes_array import BoxesArray


class TestBoxesArray(unittest.TestCase):
    """ BoxesArray unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBoxesArray(self):
        """
        Test BoxesArray
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = stylelens_feature.models.boxes_array.BoxesArray()
        pass


if __name__ == '__main__':
    unittest.main()
