# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gallochri/dev/glMAC/glMAC/resources/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("image: url(:/images/images/logo32x32.png);\n"
"font: 75 20pt \"Open Sans\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_services = QtWidgets.QLabel(self.centralwidget)
        self.label_services.setObjectName("label_services")
        self.verticalLayout_2.addWidget(self.label_services)
        self.comboBox_services = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_services.setObjectName("comboBox_services")
        self.comboBox_services.addItem("")
        self.comboBox_services.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_services)
        self.label_input_mac = QtWidgets.QLabel(self.centralwidget)
        self.label_input_mac.setObjectName("label_input_mac")
        self.verticalLayout_2.addWidget(self.label_input_mac)
        self.input_mac = QtWidgets.QLineEdit(self.centralwidget)
        self.input_mac.setObjectName("input_mac")
        self.verticalLayout_2.addWidget(self.input_mac)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.button_search = QtWidgets.QPushButton(self.centralwidget)
        self.button_search.setObjectName("button_search")
        self.verticalLayout_3.addWidget(self.button_search)
        spacerItem = QtWidgets.QSpacerItem(20, 270, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_output_vendor = QtWidgets.QLabel(self.centralwidget)
        self.label_output_vendor.setObjectName("label_output_vendor")
        self.verticalLayout.addWidget(self.label_output_vendor)
        self.output_vendor = QtWidgets.QLineEdit(self.centralwidget)
        self.output_vendor.setEnabled(False)
        self.output_vendor.setObjectName("output_vendor")
        self.verticalLayout.addWidget(self.output_vendor)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 23))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/application-exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon)
        self.action_exit.setObjectName("action_exit")
        self.action_about = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/QtIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon1)
        self.action_about.setObjectName("action_about")
        self.menu_File.addAction(self.action_exit)
        self.menu_Help.addAction(self.action_about)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.action_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "glMAC"))
        self.label.setText(_translate("MainWindow", "glMAC                         "))
        self.label_services.setText(_translate("MainWindow", "MAC address lookup services:"))
        self.comboBox_services.setItemText(0, _translate("MainWindow", "MacVendors.co (default)"))
        self.comboBox_services.setItemText(1, _translate("MainWindow", "MA:CV:en:do:rs"))
        self.label_input_mac.setText(_translate("MainWindow", "MAC Addresses"))
        self.button_search.setText(_translate("MainWindow", "Search"))
        self.label_output_vendor.setText(_translate("MainWindow", "Result:"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.action_exit.setText(_translate("MainWindow", "&Exit"))
        self.action_exit.setShortcut(_translate("MainWindow", "Alt+E"))
        self.action_about.setText(_translate("MainWindow", "&About"))
        self.action_about.setShortcut(_translate("MainWindow", "Alt+A"))

from . import mainwindow_rc
