
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-17T16:07:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a8b132bd2830daa95760c7663a1bf49d60e4aa7",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
