
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "76abd3eb886c5af2222322b1e998da15f893f94a",
 "version": "v0.1.1-alpha.post.dev29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
