



##############################################################################################################
#
# NOTE !!!
#
# THIS FILE MAY BE AUTOGENERATED.
# ONLY MODIFY THE ORIGINAL FILE IN THE /sharedData/ FOLDER!
# OTHER INSTANCES OF THIS FILE ARE COPIES!
#
# NOTE !
#
##############################################################################################################


class ServersideProgrammingError(Exception):
    """
    this exception shouldn't happen during the normal course of operations.
    If it does, someone needs to debug this.
    """
    pass


class AdminFuckedUp(Exception):
    """
    this exception should only occur in Django commands that didn't work properly.
    """
    pass


class AccessRightsException(Exception):
    """
    an exception that indicates that an illegal operation was requested.
    """
    pass


class InvalidParamsException(Exception):
    """
    an exception that indicates that a parameter given to the server is invalid.
    """
    pass


class BenignException(Exception):
    """
    an exception that is benign. It is supposed to happen and can be ignored. It does not need to be reported.
    """
    pass
