sudo: required
dist: trusty
services: docker
language: python
python: 3.5
cache:
  timeout: 600

notifications:
  webhooks:
    urls:
      - secure: "W79aUtJ3BOWVGbTQ0jzIeDvF6Z8byJegtAa9zW6L8Ij9MyfM5sEcJzHDyAnmLVsPf+P3KkzTHS5HYNodznENyeMcLwbFtuiDb1FrprzE+z2YqLrcudDAIjwOCpMmitYnaq9uZyuRuN8LSG7iJxOq3txIrbvRpVxVJZPvH95SzFOtERlPwpGGj4huF6JRFnjInZhxjJ1jQUWGeQni+aeBs2usK63I4kpG430oBnwy2INi2I5+lnSctCIX8SMbh8iXrBGNCJ7uer95xxy6bHh1OfE6PjpmKSn7siIplh70hCMGNwui+ux1cgcH+PTPJ/7ZsyqU+s8surtMnqHowCqZ7vK/N/cmI8rT8DGrfL+hwBMerb1NfWWRw1756f8vYmEgdS5pcb84tZ6p9P48Gh+Dx49dI9+H5r4CrM7B6/yXgklijqcBScHLBXs6kcdUvVteTyT2jHyme/dRxlFjdgcWlm9H/pR2xDHcSp0I7fl0YlCai0/d0z85sWz2brcZ+SKqxxEQTm8oDrWaadNBr8h6b1/tpc539/WMw2ONjCG3+y/I5T2gMbXdcc/KxHQBmpcFWpdQBarjs5TLQ9LyqKX1yBBSCJGC56+U0rPcQML0BZNnKwNKKvogY3izFd6hhmXDQ5W4l6wZS/taup1XWYU4+XjBkNursAKcttyoxfu0JMw="
      
jobs:
  include:
  ######################## XENIAL - TESTS
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_TESTS=ON'
    - TEST='TRUE'
    - CC_VER="5"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

  ######################## XENIAL - Python
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_PYTHON=ON'
    - TEST='TRUE'
    - CC_VER="5"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

#  ######################## XENIAL-EMSCRIPTEN
#  - stage: build+test
#    os: linux
#    env:
#    - PLATFORM='xenial-emscripten'
#    script: "./travis/build.sh"
#
#  ######################## OSX + TESTS
#  - stage: build+test
#    os: osx
#    if: branch = master
#    env:
#    - CMAKE_ARGS='-DBUILD_TESTS=ON'
#    - TEST='TRUE'
#    script:
#    - "./travis/build.sh"
#
#  ######################## OSX
#  - stage: build+test
#    os: osx
#    osx_image: xcode9.1
#    if: branch = master
#    env:
#    - CMAKE_ARGS='-DBUILD_PYTHON=ON'
#    script:
#    - "./travis/build.sh"


  ########################
  - stage: publish
    if: tag =~ ^v
    os: linux
    env:
    - CC_VER="5"
    - PLATFORM='xenial'
    - DEPLOY='TRUE'
    script:
    - sudo pip install -U pip setuptools twine
    - "./travis/build.sh"

    deploy:
      provider: pypi
      skip_cleanup: true
      user: deployqrl
      password:
        secure: bZxMw6W3WxarfdTR8tvzc4tv5u92IHqP6mw2b0Qm2u3QrHfFr7ZPspedlFHBGF9sx8Lpprn6eeonodBfAEFTZiaQ+JwsLUFyMpIdMnkALWXukIp1LYv1Paj6hqhGYv/sBE2kvsAVzxJRCiIGFc5wnboIxztI4XsnF/OqblVO8DFYTsSlNrIDmwX+Nk5ltL32yOCrsOL0koGt2IDCDUTy848LT4GdL+xOLEW1Pq4R0nFJ0lBN/qOCZHN9wj6+VQGPfiYP0ePzedeAPtYhOXfaJUSnLYYamIqpL2g3X1Q93RKpq+epUDDp7hMT2avF3fV+x9ArW3k4/GKld/vndP+VOmMVyEL1Kj6F7fFzm4dnh7yyf0+DweUSQNiYdJtclyX9yZwKrM3kDSg4PpQ8eMOf8IqVFo75hbx51T072tPE06kir/VUyJ1t3Y8fJZroIIq6ayYPuosf56k2/+T0RrFKSyTeVf9vG+mPM7azQHuU77MOqR7tW7caxbTTuSIpgmYqW7nAggCVJqELoNAQeJfz9tVeLEsn2jLo1CsJikkCQIWXn6JXT+NGslGY5MQTxeEd9+2A7qmsxXs9ZXlkhNSAqlSaMzO5Ao0AdniAiEc3YKoHgPPs9LfB1mXdc3Bl6fToWMd23AmLCIm37TuyCOTs/qf2m/CSqX3bj/a12NOoMu4=
      on:
        tags: true
        all_branches: true

#  ########################
#  - stage: publish
#    if: tag =~ ^v
#    os: linux
#    env:
#    - PLATFORM='xenial-emscripten'
#    script:
#    - "./travis/build.sh"
#    - "./travis/patch_npmversion.sh"
#
#    before_deploy: npm version
#
#    deploy:
#      provider: npm
#      skip_cleanup: true
#      email: "info@theqrl.org"
#      api_key: $NPM_API_KEY
#      on:
#        tags: true
#        all_branches: true
