
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-26T12:38:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d51ed4a7d1e2e1c14ba68367da5c9a56172eabb8",
 "version": "0.5.10.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
