
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5b2b9316f8d1d1d78a30e0f378ba46e9cbd268ff",
 "version": "3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
