# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0096_auto_20180511_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Order Created By'),
        ),
        migrations.AddField(
            model_name='order',
            name='printed_status',
            field=models.BooleanField(default=False, verbose_name='The Order Print status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('w', 'Wholesale'), ('r', 'Retail')], default='r', max_length=50, null=True, verbose_name='Order Type'),
        ),
    ]
