# Generated by Django 2.0.4 on 2018-04-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packrat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoardfile',
            name='content_type',
            field=models.CharField(default='image/png', max_length=32),
            preserve_default=False,
        ),
    ]
