#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nbopen']

package_data = \
{'': ['*'], 'nbopen': ['icons/*']}

install_requires = \
['notebook', 'nbformat']

entry_points = \
{'console_scripts': ['nbopen = nbopen:main']}

setup(name='nbopen',
      version='0.6',
      description='Open a notebook from the command line in the best available server',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://github.com/takluyver/nbopen',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.5',
     )
