language: python
sudo: false
python:
  #- "3.5"
  - "3.6"
env:
  global:
    - secure: oaJ4/I5yYkryQW2ANWkefp6PwmdGk5L0g5BdSxnGQiH8jdsqS30Nd0LmbUzkklDigaiTb9UIvrPQdrx+tHXoPsyaT6UXr0YRvht1vw4gbDt61+ECWuFgcTECX0A9U/JrDXonaKmeu5UZEpCNrAgAQR1ZsMGaJ2QpVfBtpQZUdwCAPBchFLheK2yr54dzCG9s4yZHJWculTja5rTb/mIqRfze3EIxX5sGjyDYNEVfvqwCu729pO9xd8ZaP1TZtQzltgfSzkMH6/cnzgGLPfKV7yWsJFj0AYOilvcc+XLfgfO76fA4qhchYJJog9+CWTdE48VA0v53YlIud70yPKucTE795zDsLsUqz8FIEYcMNrzm0jKIHp6AZK7MEq6VzRnjmBdgJX2UaHNsKr+0KcM+zbhwMJ3ABMKq3mtjcRnWEkmjwgLdH+DrDhZK/SWIlpVCU1blbiArgHhaGisfyLIHG4406O1Nw+dTrp+HmDU5MsUGp5S6eo7TS/lkTj/11hqDQcjfcReHPqFqUobOvjBEV7jpEgGWUeM2wwf/IGKLbI8A8vGh84Ki9I7v1RPjm2C4GRAPUMdSfbekLTbSyPv3Ul2JmhyAx8tPHEiSe82hjhkiq5S+K6YRgZCPXkDo7kPmu7LY4hhnTpugQUrlhIqDzqxJZjcVpM1tzdoPV83FxLY=
install:
  - pip install --editable .
script:
  - env
  - satsuki --user YakDriver --repo pyppyn --latest -v
  #- pytest
before_deploy:
  - |
    if [ "$TRAVIS_BRANCH" = "dev" ]; then
      sed -i -E "s/^(version = )(.*)/\1\2.$TRAVIS_BUILD_NUMBER/" $TRAVIS_BUILD_DIR/setup.cfg
    elif [ "$TRAVIS_BRANCH" = "master" ]; then
      export RELEASE_VERSION=$(grep "version = " $TRAVIS_BUILD_DIR/setup.cfg | sed "s/version = //")
      export RELEASE_BODY="* [satsuki v$RELEASE_VERSION CHANGELOG](https://github.com/YakDriver/satsuki/blob/$RELEASE_VERSION/CHANGELOG.rst)"
      (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
    fi
deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    user: YakDriver
    password:
      secure: T/Wwu4XR1ga4Olp/cgAxDrxt1jLY+YinOOJEogJJAHi9rBm0McLaaTPRLfkTG8OtB2vQ+lOBHVFfjSMjYxXtqCvzibO2mRHjX8vXUQxz4FBtIfw7AudwasKlKax+eHRfsJbFYipauIW+JUC80q3G21PwJjXqPotOhBGamCoIzo0TEV7+TEPBmLwKKJ/9ZskDVgvnoTwcDU3d0ioi6Ib0fEYTLx6EQUNuhFEkZUZgtjULesUVB+Rc9XWl2xle20yVVhD37q/gS5+4JPYkGp/ohNM0pZVkwqnsnxTn988uFYl+M79KzevoClmMnxEZp+b1y/URsGFggzzYo5ClAJVraBfInbtqhP+NuhDMhN8VoP8L2RxcGR+Ym5vhFnfDd2fSR2htx209abyxQ1QM9zYVBWWPPb/CgAY7Y4W8ZQPw+7bgIzQANSJNlUakZn+5vKEyim8PekiMogHzcb7wWv8SpwZM+UOZrFWtxsVksqQMS5e8E3EjAsO3gIRHx+81c2eguiXICs4x9Ipo0Xo1F6m8RhNoZEagPFSRnQbz5FHJcUzco5WHx5mgU7LWWqqI/JghRLVhzc5U8S6rPHdHObmCVF1vNfug10sKpkL/+BlogDR/sqioOUFdYyv4OaGbMUwwJHevbenZZQgPt2o8GmBTKiaEoOz7gpHFdyFgrXi2wzs=
    skip_cleanup: true
    skip_upload_docs: true
    on:
      branch: dev
      repo: YakDriver/satsuki
      python: "3.6"
  - provider: releases
    name: $RELEASE_VERSION
    tag_name: $RELEASE_VERSION
    target_commitish: $TRAVIS_COMMIT
    body: $RELEASE_BODY
    draft: false
    skip_cleanup: true
    api_key:
      secure: Mj4uJ7DHHnihcVyi1kc1ZiNVVmKgGg4+6bIGfbqEmvIeKMom5PaR1l5ZnOHPcPkBROS+WkCNnr8AehljBtMIjuC7M4s5gSf9euTu4pzft3TS5qAgWwxw1SlI6LylvzEQG++to9C6WO9ioIlUbcbzfgUAGKlEgbNJ9EuWZ6l+WIDdPtbQ/7JBJkp8zi4DAEryeKyGnxc8w+iAkpXGdoQxXGp0mUcacQ3M5Z/luRQpf/qgkKGx5/sM72ufN7bO32sdNJp4GoY4BLTaQO5xGbPB/yWGU0qrrn+JTIy3foXdbzK0jqQXtrF2h/F80C0TIOksB6Kwx0qBksIUk61S3OBdTnCgDz5dElgwGcTgyc4DJn88uEKVksr/A0YJ+ypXhVUgypqMYke4pTdYstzwD5oPrVZ7NMUMJztz6a/uNt35AY/NWQqFPasjuDWbUypVbxdsriytZp8NdsfmDET/UGMwilgNfIapIQPu3R7Otv6KbGoNHhlM/vJ9rhBV6YlM/P2unFSQdT9HXOlEILbqBzR2jy+ytdUOcwSXU6rw+UyMeoHqjXqHTXpjoVK5gM/fCsvVngJKMPpyU387LnmUvfIYgObhD6FU/QIBVlixDRErVS6RDRICDXxncb8uyJLpqn4Ch3MzBZZ7D+irOI7/8F9z0/oaKR7uA9ObYDage85pm3A=
    on:
      branch: master
      repo: YakDriver/satsuki
      python: "3.6"
  #- provider: pypi
  #  distributions: sdist bdist_wheel
  #  user: YakDriver
  #  password:
  #    secure: jnXWuNMooLvNezR9juAZw/9yVuazxCsdBK1eHCABcTBni6PsFwmTUGFyuz0gC4CCagf4RAvd8D6dt0I0KUnaL37FMlMsxcLbjY9wcsT2DitTYTLaPcyIUylXPJpobaqcjNqAksquS6R0w13xN5sXuJLKqzalaNNfwts6x4S41xbbj1gtpUifAugHT94CQVf4apMrUOSyvcqfijo6wv4Kp0VyX9X1rPqkQEsMgdLeOeZAEBYe9aJUV5r9t6C0BDhKKySus5j8kZuNt5xjTsN8/4VMJapKhMW6xjiRui4a1c34D+g/q53fvvA+O3Behh/jdPRK8fRyVVfLACzx65eYFnuN92yDUn4IiQlL/wBKQWX4Zh8qcevXYTqh8tYsyoenWuBxhJQQXdACoFUk4t89onFy1BCvNEjGKcPesZcU7LOZwvSBoyI2Sik6xLLjINgCVrcxgVEZs72DWiY0aVDEzHasLzdRiY4mWp4KBi4AsElfVa2ARLUCKZMZu7amSOYumfOttGljGX5/woW7eHKt8gKbwBGRWGPpMq/qOOivOTgV20eXX/DO4NwreMGLmlThsVQtxYZYTlUdYiKR6Px1Z+ZrNNu+cK2eIKaA32i5ksZqI9sN4nY34Mu323qMvHnzq1TcQKy58ers3rf0NTGSFwoYhOKVVL1jHGde69tBPzo=
  #  skip_upload_docs: true
  #  on:
  #    tags: true
  #    repo: YakDriver/satsuki
  #    python: "3.6"
