
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-24T14:30:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba555f34e3855f6db1e7464ed6c53906b5831656",
 "version": "0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
