language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - TRAVIS_PYLINT=false

matrix:
  include:
    - python: "3.6"
      env: TRAVIS_PYLINT=true

# command to run tests, e.g. python setup.py test
script:
  - echo hello
deploy:
  - provider: pypi
    user: vmalloc
    password:
      secure: EBE30QsQvwodsakJRtXvmeah0KRQoMpHQSfSACjE0FviWU6eHhgE7nSzxrTSwetmLaB/+hexkys8ULsE4Dxwgvd8aXJ5T6+GnhFkWLgaTl8Q39g/cnLqnVj+OCS95XlyFcWyBLsdyPY+tAc34YpYRfjuWgXup5UNc7Ze2KQ7wqk=
    on:
#      tags: true
      branch: bugfix/readme
      repo: getslash/slash
      python: "3.6"
      condition: $TRAVIS_PYLINT = 'false'
