# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=py2-cover,py3-cover,coverage
        - python: 3.6
          env: TOXENV=docs
        - python: 3.6
          env: TOXENV=pep8
        - python: nightly
          env: TOXENV=py37
    allow_failures:
        - env: TOXENV=py37

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
  irc:
    channels:
      - "chat.freenode.net#pyramid"
