environment:
    global:
        VERBOSE_SUBPROCESS: 1
    matrix:
        - PYTHON: "C:/Python36"
        - PYTHON: "C:/Python36-x64"
init:
    - "set PATH=%PYTHON%/scripts;%PYTHON%;%PATH%"
    - "python --version"
    - "pip --version"
    - "set TINYSHAR_TEST_RUN_WRAPPER=%APPVEYOR_BUILD_FOLDER%/busybox.exe sh"
install:
    # - "pip install --disable-pip-version-check --user --upgrade setuptools pip"
    - "pip install -r requirements-dev.txt"
    - "pip list --format columns"
    - "choco install shellcheck"
    - "shellcheck --version"
    - "mkdir bin"
    - "curl -fsSL -o busybox.exe https://frippery.org/files/busybox/busybox.exe"
    - "busybox"
build_script:
    - "inv check"
test_script:
    - "inv test"
