
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-23T16:58:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "920d32849c4d0824ca4b90c2975986c145b8c346",
 "version": "v0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
