
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-17T22:38:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "77ebff025028bfdd6fb2dc87be4351190d1c1681",
 "version": "v0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
