
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-04T14:52:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4804886f9a5a576558e62380d1bd9dad22e7733",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
