{% set flavor_name = flavor_name or "m1.tiny" %}
{% set image_location = image_location or "http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img" %}
---
  GlanceImages.create_image_and_boot_instances:
    -
      args:
        image_location: "{{ image_location }}"
        container_format: "bare"
        disk_format: "qcow2"
        flavor:
            name: "{{ flavor_name }}"
        number_instances: 2
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 3
          users_per_tenant: 5
      sla:
        failure_rate:
          max: 0
