
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-20T13:59:55-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf859159c4b574dd869e41d87541966cfc6b2575",
 "version": "v0.9.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
