#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='astcheck',
      version='0.2.5',
      description='Check Python ASTs against templates',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://github.com/takluyver/astcheck',
      py_modules=['astcheck'],
     )
