
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-25T22:36:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e47f1604970bfb2aff0b6b66abf47b3538f554d",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
