
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-24T09:55:05-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4e67c46cec67b8b7830bc8132d5523f2f8b35d7",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
