
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-15T14:46:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fe04cde60f87fe80e845ec94f377a26e81f201f",
 "version": "3.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
