language: python

python:
    "3.6"

before_install:
  - pip install codecov

install:
    pip install -r requirements.txt

script:
    pytest --cov=cryptopcash

after_success:
  - codecov --disable search --token=3dffbce2-6af2-46cb-9638-a30cdad43672
