# coding: utf-8

"""
    AutoTec Services API

    API for methods pertaining to all AutoTec services  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import autotec
from autotec.models.vehicle_scoring import VehicleScoring  # noqa: E501
from autotec.rest import ApiException


class TestVehicleScoring(unittest.TestCase):
    """VehicleScoring unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleScoring(self):
        """Test VehicleScoring"""
        # FIXME: construct object with mandatory attributes with example values
        # model = autotec.models.vehicle_scoring.VehicleScoring()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
