# coding: utf-8

"""
    AutoTec Services API

    API for methods pertaining to all AutoTec services  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import autotec
from autotec.api.default_api import DefaultApi  # noqa: E501
from autotec.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = autotec.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vehicle_history_full_options(self):
        """Test case for vehicle_history_full_options

        """
        pass

    def test_vehicle_risk_options(self):
        """Test case for vehicle_risk_options

        """
        pass


if __name__ == '__main__':
    unittest.main()
