# coding: utf-8

"""
    AutoTec Services API

    API for methods pertaining to all AutoTec services  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import autotec
from autotec.models.empty import Empty  # noqa: E501
from autotec.rest import ApiException


class TestEmpty(unittest.TestCase):
    """Empty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmpty(self):
        """Test Empty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = autotec.models.empty.Empty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
