language: python
sudo: false
services :
 - docker
python:
 - 3.5
 - 3.6

addons:
  apt:
    packages:
    - slapd
    - ldap-utils

env:
 - DATABASE_URL=postgres://postgres@/karaage
 - DATABASE_URL=mysql://root:@localhost/karaage
 - DATABASE_URL=sqlite://

install:
# Install database drivers
  - bash -c "if [[ $DATABASE_URL = postgres* ]]; then pip install psycopg2==2.7.3.1; fi; "
  - bash -c "if [[ $DATABASE_URL = mysql* ]]; then pip install mysqlclient==1.3.12; fi; "
# Install other dependancies
  - pip install -rrequirements/tests.txt

before_script:
  - psql -c 'create database karaage;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS karaage;'

script:
  - isort -rc --check --diff karaage
  - flake8

  - ./manage.py makemigrations --settings="karaage.tests.settings" --check --dry-run
  - ./manage.py collectstatic --settings="karaage.tests.settings" -v 2 --noinput
  - ./manage.py test --settings="karaage.tests.settings" -v 2 karaage.tests

  - ./manage.py makemigrations --settings="karaage.plugins.kgapplications.tests.settings" --check --dry-run
  - ./manage.py collectstatic --settings="karaage.plugins.kgapplications.tests.settings" -v 2 --noinput
  - ./manage.py test --settings="karaage.plugins.kgapplications.tests.settings" -v 2 karaage.plugins.kgapplications

  - ./manage.py makemigrations --settings="karaage.plugins.kgsoftware.tests.settings" --check --dry-run
  - ./manage.py collectstatic --settings="karaage.plugins.kgsoftware.tests.settings" -v 2 --noinput
  - ./manage.py test --settings="karaage.plugins.kgsoftware.tests.settings" -v 2 karaage.plugins.kgsoftware.tests

  - ./manage.py makemigrations --settings="karaage.plugins.kgsoftware.applications.tests.settings" --check --dry-run
  - ./manage.py collectstatic --settings="karaage.plugins.kgsoftware.applications.tests.settings" -v 2 --noinput
  - ./manage.py test --settings="karaage.plugins.kgsoftware.applications.tests.settings" -v 2 karaage.plugins.kgsoftware

  - ./manage.py makemigrations --settings="karaage.plugins.kgusage.tests.settings" --check --dry-run
  - ./manage.py collectstatic --settings="karaage.plugins.kgusage.tests.settings" -v 2 --noinput
  - ./manage.py test --settings="karaage.plugins.kgusage.tests.settings" -v 2 karaage.plugins.kgusage

jobs:
  include:
    - stage: deploy
      if: type = push and tag =~ ^v
      install:
      script:
      - docker build
            --file "Dockerfile"
            --tag "brianmay/karaage:slurm16.05"
            --build-arg "SLURM_VER=16.05"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker build
            --file "Dockerfile.apache"
            --tag "brianmay/karaage:slurm16.05-apache"
            --build-arg "SLURM_VER=16.05"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker build
            --file "Dockerfile"
            --tag "brianmay/karaage:slurm17.02"
            --build-arg "SLURM_VER=17.02"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker build
            --file "Dockerfile.apache"
            --tag "brianmay/karaage:slurm17.02-apache"
            --build-arg "SLURM_VER=17.02"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "brianmay/karaage:slurm16.05"
      - docker push "brianmay/karaage:slurm16.05-apache"
      - docker push "brianmay/karaage:slurm17.02"
      - docker push "brianmay/karaage:slurm17.02-apache"
      deploy:
        provider: pypi
        user: "penguin_brian"
        password:
          secure: BQaJb9cNx4fX5j/eLPjyvBq20N9gd3QWtq42qgBjF68608qIWKo3BtrNG87JtN1MkdZJDDUPdTjeQnwnjYfxbZvzaiJ32i+JyO92HlBL51DdSpppMVlalO0yYDos4ZHPi61M1xOu1DGPIl6vUaYamHI8ylpf8mWeO/UBp3uuq2M=
        distributions: "sdist bdist_wheel"
