# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0090_auto_20180420_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_fname', models.CharField(max_length=255)),
                ('contact_lname', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('Broker', 'Broker'), ('Reseller', 'Reseller'), ('Non-profit', 'Non-profit'), ('Media Outlet', 'Media Outlet'), ('Retail Outlet', 'Retail Outlet'), ('Other', 'Other')], max_length=50, verbose_name='Account Type')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesales_event', to='pretixbase.Event')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[(('w',), 'Wholesale'), ('r', 'Retail')], max_length=50, null=True, verbose_name='ORDER Type'),
        ),
        migrations.AddField(
            model_name='order',
            name='wholesale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.WholesaleAccounts', verbose_name='Wholesale Account'),
        ),
    ]
