# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Description displayed to user of the usage of this Category', verbose_name='Description')),
                ('default', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Default used for new User Preference', verbose_name='Default')),
            ],
        ),
        migrations.CreateModel(
            name='UserOptin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Select to opt in', verbose_name='User Preference')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optin.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='useroptin',
            unique_together=set([('user', 'category')]),
        ),
    ]
