sudo: false
language: python
python:
  - "3.6"
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  # - pylint src/bkyml/*.py tests/test_skeleton.py
  - python setup.py test
after_success:
  - coveralls