
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-15T13:02:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2ca6eebfb1d38520e711c6fbf60f0f78c742a63",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
