
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-20T16:38:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dfb7ef5977747b3045b8bc8ff66ba09df32dc83",
 "version": "0.35.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
