
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-16T10:31:05+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4855ade615cc57f31eb07cfd0b4e9e8dbe8ef81",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
