##  cluster settings

# id: <id of the cluster to be created, reccommended to specify with --id command line parameter>

# vm_size: <vm-size, see available options here: https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/>
vm_size: standard_a2

# size: <number of dedicated nodes in the cluster, not that clusters must contain all dedicated or all low priority nodes>
size: 2

# size_low_pri: <number of low priority nodes in the cluster, mutually exclusive with size setting>


# username: <username for the linux user to be created> (optional)
username: spark

# docker_repo: <name of docker image repo (for more information, see https://github.com/Azure/aztk/blob/master/docs/12-docker-image.md)>
docker_repo: 

# # optional custom scripts to run on the Spark master, Spark worker or all nodes in the cluster
# custom_scripts:
#   - script: </path/to/script.sh or /path/to/script/directory/>
#     runOn: <master/worker/all-nodes>
#   - script: <./relative/path/to/other/script.sh or ./relative/path/to/other/script/directory/>
#     runOn: <master/worker/all-nodes>

# To add your cluster to a virtual network provide the full arm resoruce id below
# subnet_id: /subscriptions/********-****-****-****-************/resourceGroups/********/providers/Microsoft.Network/virtualNetworks/*******/subnets/******

# Enable plugins
plugins:
  # - name: spark_ui_proxy
  # - name: jupyterlab
  # - name: jupyter
  # - name: hdfs
  # - name: rstudio_server

# wait: <true/false>
wait: false
