#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mail2mongo']

package_data = \
{'': ['*']}

install_requires = \
['aiohttp>=3.1.3,<4',
 'aiosmtpd>=1.1,<2',
 'cchardet>=2.1.1,<3',
 'motor>=1.2.1,<2']

entry_points = \
{'console_scripts': ['mail2mongo = mail2mongo:entrypoint']}

setup(name='mail2mongo',
      version='0.3.3',
      description='Simple SMTP daemon which save incoming emails to MongoDB',
      author='Innokenty Lebedev',
      author_email='innlebedev@protonmail.com',
      url='https://github.com/inn0kenty/mail2mongo',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.5',
     )
