language: python
python:
    - 2.7
    - 3.5
    - 3.6
addons:
  postgresql: "9.6"
install:
    - pip install tox-travis coveralls
before_script:
    - psql -c "create user pjpersist with createdb password 'pjpersist';" -U postgres
script:
    - tox
notifications:
    email: false
after_success:
  - coveralls
