
# Generated by Django 1.10.6 on 2017-03-17 15:01


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import octo_drf.apps.base.models
import octo_drf.apps.generic_image.fields
import octo_drf.apps.generic_image.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u043e\u043b\u044f')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('placeholder', models.CharField(blank=True, max_length=255, verbose_name='\u041f\u043b\u0435\u0439\u0441\u0445\u043e\u043b\u0434\u0435\u0440')),
                ('image', octo_drf.apps.generic_image.fields.SorlImageField(blank=True, storage=octo_drf.apps.generic_image.storage.ImageStorage(), verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430')),
                ('error_message', models.TextField(blank=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043f\u0440\u0438 \u043e\u0448\u0438\u0431\u043a\u0435')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0442\u0430 \u0434\u0430\u043d\u043d\u044b\u0435 \u043f\u043e\u043b\u044f \u0444\u043e\u0440\u043c\u044b',
                'verbose_name_plural': '\u041c\u0435\u0442\u0430 \u0434\u0430\u043d\u043d\u044b\u0435 \u043f\u043e\u043b\u0435\u0439 \u0444\u043e\u0440\u043c',
            },
        ),
        migrations.CreateModel(
            name='FormMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u043e\u0440\u043c\u044b')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('button', models.CharField(blank=True, max_length=500, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043a\u043d\u043e\u043f\u043a\u0438')),
                ('error_message', models.TextField(blank=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043f\u0440\u0438 \u043e\u0448\u0438\u0431\u043a\u0435')),
                ('success_message', models.TextField(blank=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043f\u0440\u0438 \u0443\u0441\u043f\u0435\u0445\u0435')),
                ('error_button', models.CharField(blank=True, max_length=500, verbose_name='\u041a\u043d\u043e\u043f\u043a\u0430 \u0434\u043b\u044f \u043e\u0448\u0438\u0431\u043a\u0438')),
                ('success_image', octo_drf.apps.generic_image.fields.SorlImageField(blank=True, storage=octo_drf.apps.generic_image.storage.ImageStorage(), verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0443\u0441\u043f\u0435\u0448\u043d\u043e\u0433\u043e \u043e\u0442\u0432\u0435\u0442\u0430')),
                ('pattern', octo_drf.apps.generic_image.fields.SorlImageField(blank=True, max_length=500, verbose_name='\u041e\u0448\u0438\u0431\u043a\u0430: \u0421\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0438\u0435 \u0444\u043e\u0440\u043c\u0430\u0442\u0443')),
                ('require', octo_drf.apps.generic_image.fields.SorlImageField(blank=True, max_length=500, verbose_name='\u041e\u0448\u0438\u0431\u043a\u0430: \u041e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435')),
                ('url', octo_drf.apps.generic_image.fields.SorlImageField(blank=True, max_length=500, verbose_name='URL \u0444\u043e\u0440\u043c\u044b')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0442\u0430 \u0434\u0430\u043d\u043d\u044b\u0435 \u0444\u043e\u0440\u043c\u044b',
                'verbose_name_plural': '\u041c\u0435\u0442\u0430 \u0434\u0430\u043d\u043d\u044b\u0435 \u0444\u043e\u0440\u043c',
            },
            bases=(octo_drf.apps.base.models.DynamicModelFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='formfieldmeta',
            name='form_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_forms.FormMeta', verbose_name='\u041c\u0435\u0442\u0430 \u0434\u0430\u043d\u043d\u044b\u0435 \u0444\u043e\u0440\u043c\u044b', related_name='fields_meta'),
        ),
        migrations.AlterUniqueTogether(
            name='formfieldmeta',
            unique_together=set([('form_meta', 'field_name')]),
        ),
    ]
