
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-26T07:58:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "00bd5c6ef30d80ae285397cb2746b3844f504cc4",
 "version": "v0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
