language: python
python: '3.6'
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py36
install:
- pip install tox
script:
- tox
matrix:
  fast_finish: true
deploy:
  provider: pypi
  user: seignovert
  distributions: sdist bdist_wheel
  password:
    secure: E3tHeRrWoAKcZwF3r96mXiJFmjtVikyX27hPPzWOyK4UYJVMWe6VuhdtYvAvx/QSHxgV6ep0+Co8G0D4MnF5q6B8o+/9OgUG2aCYzeA91NBWeiHwawsVyS2rXAzYlc/YaSuGsPPkHg/lxScF9SPEpuQUGJPwR3QIXsJW8GdA2SohYkK3SvMI6mecV1goyvmKLDgPUIAQBAa0gbmNOsvkUabz9U4K3Gr/zuFMIobdYCcsRccRJFdGhz4ymrbfDZZCAKEguHJ3qyZXFgxKs4deF9boSB5zwQLmbWBYqmHaMNoEkdH0XiVKbiGiuoB3kBcXP+YRKI5wVjynVydBw7keSdpLaFZVCmSTcPHxRgwkNoISx826/sARf2EFLYEBAN2imxcAml/cn30GGypEsSByJyPdvQYnFABUzkm77gx2NbTvp6OL+nDFn87b/528qNS5TKiDIVtZOz77MlhjhalEDzF8lq4bKf4TgTJlgfGji0513omaH2pi24jsF521L/JifcrpE18KmHr3EYgCN3qvl5xrp+ht8qO+ISi6Tn/kQjSm7ny+DGSsoYeEAxKSu/FqO+087nFVq5ylZ7waonzPGEH1gxOkNwTmGJgjCJJHbY6qT7YV9iXd9MeKwtwhY4bEE0tBaIzjDEwyV1VCsmADZBBCYVLY0M4MNJSCjgU/O44=
  on:
    tags: true
    repo: seignovert/pyvims
    condition: "$TOXENV = py36"