[tool.flit.metadata]
module = "url_checker"
author = "cw-andrews"
author-email = "cwandrews.oh@gmail.com"
home-page = "https://gitlab.com/cw-andrews/url-checker"
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.6"
requires = [
   "attrs==17.4.0",
   "certifi==2018.4.16",
   "chardet==3.0.4",
   "colorama==0.3.9",
   "idna==2.6",
   "Logbook==1.3.3",
   "more-itertools==4.1.0",
   "pluggy==0.6.0",
   "py==1.5.3",
   "pytest==3.5.1",
   "requests==2.18.4",
   "six==1.11.0",
   "urllib3==1.22",
   "wincertstore==0.2"
]