
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-26T11:26:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9cb564ac94ada24dc3d2f60f6f598e1f574c08d8",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
