
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-23T10:59:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a98a0238bc7c30aa6bf6defbfcac4ebccf93f1e",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
