
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-17T22:48:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "184c55c784698f76c4c90235c1a012a5a57dd886",
 "version": "v0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
