image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

environment:
  PYTHON: "C:\\Python36-x64"

build: off

install:
  # update path to use installed pip
  - set PATH=%PYTHON%\\scripts;%PATH%
  # Install python packages
  - "%PYTHON%/Scripts/pip.exe install twine"

test_script:
  # test/hello
  - "%PYTHON%/python setup.py develop"
  - "%PYTHON%/python -m unittest"
  #- "%PYTHON%/python setup.py develop"
  #- "clang-build -d\"test/hello\" -V"
  #- 'build\main.exe'
  # test/mini-project
  #- "clang-build -d\"test/mini-project\" -V"
  #- 'build\main.exe'
  # test/mwe-toml
  #- "clang-build -d\"test/mwe-toml\" -V"
  #- 'build\runHello.exe'
  # test/external-project
  #- "clang-build -d\"test/external-project\" -V"
  #- 'build\myexe\runHello.exe'
  # test/lib-and-exe
  #- "clang-build -d\"test/lib-and-exe\" -V"
  # TODO: need to copy build/mylib/mylib.dll into exe's directory
  # - 'build\myexe\default\bin\runLib.exe'