
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-25T23:27:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4c589a2b61e77fc9fb8591dfc8e866aa588b288",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
