
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-11T10:30:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d87d1d633792e4ec35d6db90131f42b89843fa1",
 "version": "0.1.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
