
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-09T16:29:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "be870f56bcb550b031f73d48063babf4450c8c9e",
 "version": "0.1.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
