
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b23093eac4f193c638c90494ece59ab42c94cf78",
 "version": "0.5.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
