
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-20T15:34:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e263a640bdb20be8c612166069f195f0a0778de7",
 "version": "0.10.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
