
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-22T10:25:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9153a8f3630bca3ed82bcee51eadfa8c029fc59",
 "version": "0.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
