
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-03T08:48:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b09a667951d6b69a8f0b5d890f1362188f5f3efe",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
