
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-28T22:27:39+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb75f62579ed720219d45bed7cb618bb84d9a591",
 "version": "0.63.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
