
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-26T15:50:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cd13c8e652172a396c1d70d294c6c3a727095c8",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
