from distutils.core import setup


setup( name = "neocommand",
       url = "https://bitbucket.org/mjr129/neocommand",
       version = "0.0.0.35",
       description = "intermake extension for creating Neo4j driven applications.",
       author = "Martin Rusilowicz",
       license = "https://www.gnu.org/licenses/agpl-3.0.html",
       packages = ["neocommand",
                   "neocommand.api",
                   "neocommand.api.plugin_classes",
                   "neocommand.api.plugins.basic",
                   "neocommand.api.plugins.exportation",
                   "neocommand.core",
                   "neocommand.data",
                   "neocommand.drivers",
                   "neocommand.endpoints",
                   "neocommand.helpers"],
       entry_points = { "console_scripts": ["neocommand = neocommand.__main__:main"] },
       python_requires = ">=3.6",
       install_requires = ["PyQt5",
                           "typing",
                           "keyring",
                           "colorama",
                           "py-flags",
                           "mhelper",
                           "progressivecsv",
                           "neo4j-driver",
                           "py2neo",
                           "editorium",
                           "intermake",
                           'stringcoercion']
       )
