[metadata]
name = 'kecpkg-tools'
version = '0.0.1'
description = 'packaging tools to assist in the creation of new kecpkg KE-chain executable SIM packages.'
author = 'Jochem Berends'
author_email = 'jochem.berends@ke-works.com'
license = 'Apache-2.0'
url = 'https://github.com/_/kecpkg-tools'

[requires]
python_version = ['2.7', '3.5', '3.6', 'pypy', 'pypy3']
requires = ['click', 'atomicwrites', 'jinja2', 'hatch', 'pykechain>=1.13']
testing_requires = ['coverage', 'pytest', 'toml', 'flake8', ]

[build-system]
requires = ['setuptools', 'wheel']

[tool.hatch.commands]
prerelease = 'hatch build'
