
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-24T18:10:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "133e1ff20e6ce7dc8c897b714125a93c76b89cb6",
 "version": "0.1.0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
